### ISSUE TITLE
localdb section in config.ini.example incorrectly named

### ISSUE THREAD

**Issue by otherguy** [muldjord/skyscraper#101]
~I'm not yet 100% sure but it looks like the option inheritance in `config.ini` is wrong.~

UPDATE: as noted in https://github.com/muldjord/skyscraper/issues/101#issuecomment-452930185, the `localDb` section in [`config.ini.example#L58`](https://github.com/muldjord/skyscraper/blob/master/config.ini.example#L58) needs to be renamed to `localdb`.

**Comment by muldjord** [comment]
It's because the section for the localdb scraping module is called '[localdb]' and not '[localDb]'. I realize how that can be confusing and I'll probably change 'localDb' to be 'cache' instead.

**Comment by otherguy** [comment]
@muldjord not at all! `localdb` is perfectly fine and it's what I would have expected the section name to be.

However, in [`config.ini.example#L58`](https://github.com/muldjord/skyscraper/blob/master/config.ini.example#L58), the section is named `localDb`.

I will rename the ticket, maybe you can reopen and address it.

**Comment by muldjord** [comment]
I'm not sure you understand. There are to distinct sections. One called "localdb" and one called "localDb". The latter is the one that tells Skyscraper what to cache and is NOT related to the module. The former is the one where you can set any configs for the localdb module.

So I will keep the "localdb" section, of course, that's not gonna change. But I will rename the "localDb" section to "cache" or maybe just incorporate it into the main section instead.

**Comment by otherguy** [comment]
Ugh, you're right, I missed that -- it was 2am after all 😅  Thank you for clarifying, though! Now, during the day, that does make sense.

Yeah, I'd rename it to `cache`, that seems more logical -- probably also better than integrating it into `main`.

**Comment by otherguy** [comment]
@muldjord no, we're back to the original issue of inheritance.

```
[main]
pretend="true"

[localDb]
noResize="false"

[localdb]
pretend="false"
```

Also does not work -- the `gamelist.xml` file is not written, if I run with `-s localdb`.

**Comment by muldjord** [comment]
The scraping module sections only allows the options stated in the config example file, so that's why that won't work. Why are you trying to add "pretend" to the localdb module section? This doesn't make any sense to me. It would be obsoleted in 3.0.0 anyway as all modules will write no game list from that release onwards. So pretend is only relevant for "localdb" after 3.0.0. And adding pretend to its section in config would serve no purpose as I can come up with.

These are the options allowed in the scraping module sections, as per the config example:
```
[scraping module (eg. 'screenscraper')]
userCreds="user:password"
threads="1"
maxLength="10000"
interactive="false"
```
The overrides will work for those. Cli overrides always takes precedence over everything else.

**Comment by muldjord** [comment]
No, pretend is not under the scraping module sections, only under the `main` section and the platform specific sections.

Could you explain why you'd want `pretend` under the `localdb` section? You say it's a pity you can't do that, but I'd be willing to consider it f you have a meaningful use case for it. I just can't come up with one myself.

**Comment by otherguy** [comment]
I'm not sure I'm doing that correctly, but I have a shell script that looks roughly like this:

```
MODULES=('openretro' 'screenscraper' 'thegamesdb' 'mobygames' 'igdb' 'localdb')
for module in "${MODULES[@]}"
do		
  /bin/skyscraper -p ${platform} -c "${SKYSCRAPERDIR}/config.ini" -d ${dbdir} -i ${romdir} --nosubdirs -t ${THREADS} -s ${module}
done
```

Now that would work if `--pretend` could be set for all modules except the `localdb` modules. Since that doesn't work, I need to do it like this:

```
MODULES=('openretro' 'screenscraper' 'thegamesdb' 'mobygames' 'igdb')
for module in "${MODULES[@]}"
do		
  /bin/skyscraper -p ${platform} -c "${SKYSCRAPERDIR}/config.ini" -d ${dbdir} -i ${romdir} --nosubdirs -t ${THREADS} -s ${module} --pretend
done

/bin/skyscraper -p ${platform} -c "${SKYSCRAPERDIR}/config.ini" -d ${dbdir} -i ${romdir} --nosubdirs -t ${THREADS} -s ${module}
```

But maybe my approach is too convoluted in the first place. All I want is to scrape all roms, in all directories (using different scraper modules per platform -- e.g. worldofspectrum for zxspectrum) and specifying a custom "home folder" for Skyscraper where it stores its `config.ini` and all databases/caches. As far as I know, that is not possible... yet?

**Comment by muldjord** [comment]
I think I get what you mean. You want pretend enabled on everything but localdb, right? In that case you'll be glad to know that this is the default behaviour from 3.0.0. From 3.0.0 "--pretend" will be enabled for all modules by default, except when scraping with localdb (in which case it will be off). This is done to prevent the other modules from creating a game list and compositing the artwork during what I will refer to as the *gather* phase. So that will solve your problem without the need to specify it in the config.ini. Scraping with `localdb` with 3.0.0 will be referred to as the *generation* phase, where a game list will be created and artwork composited.

Please let me know if this makes sense to you. It's rather simple, but difficult to explain. You can also check this new page I made a couple weeks ago that tries to explain it: https://github.com/muldjord/skyscraper/blob/master/USECASE.md

**Comment by otherguy** [comment]
Awesome, you explained it perfectly -- that's exactly what I'm looking for 😄 I'll wait for 3.0 then. Thank you again for creating this!

**Comment by muldjord** [comment]
You're welcome. I'll try and remember to post here when 3.0.0 is out. I might forget though, I have a terrible memory. :) I'll reopen the issue to help me remember.

**Comment by muldjord** [comment]
Made a change. The `[localDb]` (`[cache]`) section will be obsoleted when 3.0.0 arrives. Instead the options are moved to the `[main]` section and also allowed in `[<platform>]` sections. This allows user to cache certain resource types exclusively for certain platforms.

Note that Skyscraper 3.0.0 will automigrate these options and sections when run for the first time. So no need to do anything about it manually.

**Comment by otherguy** [comment]
Very cool! Looking forward to 3.0!

**Comment by muldjord** [comment]
3.0.0 now out :) Auto-migration will happen when you run Skyscraper 3.0.0 for the first time. Closing this now.
