### ISSUE TITLE
Invalid XML errors with Skyscraper 3.0.4

### ISSUE THREAD

**Issue by ReallyRandy** [muldjord/skyscraper#124]
Running Skyscraper 3.0.4 on a Raspberry Pie running Stretch. I have roughly 1,000 games on several game platforms. These have all been scraped previously. I tried scraping Videopac console games only and all of them (136) generated an invalid XML error.

**Comment by muldjord** [comment]
Please provide the *exact* filename of one of those files.

EDIT: I just scraped all of my videopac roms (also 136, so probably the same ones you have) without issues. Maybe this was a hiccup in the API, so please also just try again.

**Comment by muldjord** [comment]
Closing due to lack of response. Assuming fixed.

**Comment by DoubleAgentDave** [comment]
Using Skyscraper 3.0.4 just today I had a similar problems with many files, an example is listed below (md5 filename): 
cc694ca94c4d74b487983332facc8b86  Populous (UE) [!].sms

The program returned this as an error message:

ScreenScraper APIv2 returned invalid XML for the following query:
romnom=Populous%20%28UE%29%20%5B%21%5D.sms&crc=C7A1FDEF&md5=CC694CA94C4D74B487983332FACC8B86&sha1=D6142584B9796A96941B6A95BDA14CF137B47085&romtaille=262144
#275/457 (T1) Pass 1 ---- Game 'Populous (UE) [!]' not found :( ----

On a second run of the program using the exact same script generated by skyscraper it appears to scrape successfully?

This happened when scraping several romsets, master system, nes, saturn, where the first run through a lot of errors with invalid XML is found, which after a subsequent run, maybe after 2 or 3 attempts even, is successfully scraped.

**Comment by muldjord** [comment]
Yes, I've seen this happen myself aswell. It seems the API is quite unstable sometimes. I'll have to look further into what happens but there is a chance this is simply because the ScreenScraper API is unstable which means I can't really do anything about it (it's not a problem on my end is what I'm trying to say here).

**Comment by DoubleAgentDave** [comment]
I guess there isn't much you can do with that. If just been running it three or four times over each rom set, you get an exponential decay of XML errors, which seems pretty random to me.

**Comment by muldjord** [comment]
I found out why this happens. It only happens with credential-less scraping using `screenscraper` which I don't often test as I always use my credentials. Anyway, I've fixed it (well, at least the instance of this that I can reproduce) and 3.0.5 has just been released. Please update and test.

**Comment by muldjord** [comment]
NOPE! Not fixed... It just started doing it again *after* my fix. 3.0.5 withdrawn!

EDIT: I've reported the issue to ScreenScraper, I really hope this instability can be fixed. There might be nothing I can do about it on my end...

The only current workaround I can come up with is to sign up to ScreenScraper with a user, and use the credentials when scraping. I think that might make it more stable, but I am not sure. As this is a sporadic issue it's really difficult to look into properly.

**Comment by muldjord** [comment]
Screenscraper responded to the issue. It seems they have been working on a bunch of fixes, and also this one in particular over the last couple days. It should be fixed but it can take a little while for their internal server cache to catch up (this is not related to the Skyscraper cache, just to be clear). So I recommend you guys stay on top of this over the coming days and let me know if this issue persists. Thanks! I will also keep an eye on it myself.

**Comment by muldjord** [comment]
This issue has now been resolved. The reason for the faulty XML is due to a limit for unregistered users on their service. So whenever their server CPU is above a certain limit, it will return an error message instead. This error message is not XML and therefore we get the XML parse error.

The solution is to register with their service and provide the user credentials to Skyscraper as descrived in the config.ini docs.

For anyone reading, please also consider supporting them on patreon. ScreenScraper is probably the best database out there for retro gaming.

**Comment by Dcnigma** [comment]
Hey I changed the config.ini and still get a message to registered.
Tried everything...
Made a config file in /opt/retropie/supplementary/skyscraper no help
changed the suggested ~/.skyscraper/config.ini  
by uncomment the userCreds="Changed:This" but still get a suggestion to change the user credentials...
any help?

**Comment by Cee123** [comment]
Hi guys, I just signed up to Screenscraper yesterday and gave a donation. But upon scraping games (and only after putting in my credentials), it doesn't seem to work I keep getting a WebAPI Error.

Screenscraper APIv2 returned invalid XML for the following query

il manque des champs obligatoire dans l'url

But strangely enough it works using only one thread at a time if I don't put in the credentials. But due to the amount of roms I have, I'd have to leave it scraping for days if I were to use just a single thread.

Is there any news on whether the API is down at the moment?

**Comment by Cee123** [comment]
![thumbnail_IMAG0269](https://user-images.githubusercontent.com/43462099/61137817-cd04cf80-a4f8-11e9-898f-5dea78f99df8.jpg)

![thumbnail_IMAG0270](https://user-images.githubusercontent.com/43462099/61137819-cd04cf80-a4f8-11e9-9146-eda4c661a2b9.jpg)

**Comment by muldjord** [comment]
Please report this to the ScreenScraper guys. The Skyscraper project is merely using their API, not affiliated with them otherwise. This is not a Skyscraper issue it seems.

**Comment by muldjord** [comment]
User commented on other post. This was caused by a sneaky quote being in the wrong place in config.ini. No issue.
