### ISSUE TITLE
Exclude ROM extension(s) prior to hashing

### ISSUE THREAD

**Issue by kcgen** [muldjord/skyscraper#128]
I scraped a directory of ZIPs, then converted a handful to CHD.
I was surprised that SkyScraper didn't find the CHDs, even though I had positive hits on the exactly-named zip files.
It appears the games are being hashed including the extension.  This means if users adjust between any of the many formats, they will waste API hits against online resources even though they've already got the results in their cache.

For example, renaming the following through it's extensions will each require rescraping (and from multiple sources) to get a semi-complete record: 

- R-Type Complete CD (SCD)(JPN).7z
- R-Type Complete CD (SCD)(JPN).chd
- R-Type Complete CD (SCD)(JPN).cue
- R-Type Complete CD (SCD)(JPN).ZIP
- R-Type Complete CD (SCD)(JPN).CUE
- R-Type Complete CD (SCD)(JPN).CHD

So the best approach is to strip the game extension(s) prior to all cache operations to ensure users aren't hit with this _"missing cache content if extension differs"_ bug.

**Comment by muldjord** [comment]
You change the files (content *and* filename), so of course they won't be recognized.

And your assessment isn't quite correct. Some files are summed from their filenames, others from their contents. There are good reasons for both. Meddling with this would break the cache of existing users so I'm not gonna change this.

Closing.

**Comment by kcgen** [comment]
Yes, I'm only talking about the filename-based systems (not content-based systems) - which is exactly the example I gave.  
Why maintain a separate cache entry for each compression extension for the same game on the same platform? Are you telling me that MobyGames has different records for R-Type PCEngine if the filename ends in 7zip versus zip? Of course not.. therefore it makes no sense for you, downstream from the content providers, to keep separate records based on compression extension.

> Meddling with this would break the cache of existing users so I'm not gonna change this.

I see your point, but maybe that's not the only option? 

Do lookups on the old hash-with-the-extension plus the new extension-free-hash.  When you save a new cache entry, simply save the extension-free hash. So new users and existing users start to benefit from this straight away, without any old loss.

**Comment by muldjord** [comment]
It's not that simple. If you change the extension to pretty much any other type than zip, 7z and scripts, it will be summed on file content if the file is less than 50 megs (if roms are larger it takes too long, so I fall back to file name summing in those cases). So what you are suggesting won't fix what you like to call a "bug" (it's not).
I checksum file content in most cases to allow users to change the entire file name and retain the id in the cache. This is very useful when using the file name search based modules.

I *only* do checksum on file names for zip and 7z files due to how many ways you can create compressed files that will differ in size. So that's the background for that choice.

I am *not* gonna switch to a file name based checksum in general, as it would disallow users to change the file names to optimize their search results when using the file name based modules (which is every module other than `screenscraper`).

I see no reason to change this according to your wishes, as it would only work if you change between the .zip and .7z file types or if the files are above 50 megs. So it's a very niche suggestion in the first place.

**Comment by kcgen** [comment]
Thanks for the explanation. Indeed, my files are CDROM images, and therefore were larger than 50MB. I see the benefit of using content-based-IDs to allow renaming of the files.  I guess the question is - are users renaming their files more often than they are adjusting their format? (uncompressed > zip > 7zip). I should hope users are sticking with "standardized" sets from TOSEC and ReDump.  In any case - lots of trade offs.  Thanks again.
