### ISSUE TITLE
Screenscraper  "-p psx" but scrappes "-p psp"

### ISSUE THREAD

**Issue by qqplayer** [muldjord/skyscraper#13]
Hi , thanks for still working on the tool , I'm testing the lastest version but I have a problem on screenscraper.
I set "-p psx" but is setting the "psp" platform.
Can you check it?
Thanks.

**Comment by muldjord** [comment]
Please provide more information. What version of Skyscraper (I want to make sure, so please provide specific version instead of "latest version" which could potentially be anything)? Are you running it on the Pi? What is a specific filename that returns a faulty result? What does it return (copy the output and paste it here)?

Thank you.

**Comment by muldjord** [comment]
I've re-added platform checking on 'screenscraper' in the unreleased 2.3.3. Should fix this issue aswell.

**Comment by qqplayer** [comment]
Thanks I´ll try
