### ISSUE TITLE
Multiple box art

### ISSUE THREAD

**Issue by trevor7oaks** [muldjord/skyscraper#133]
The scraper is for some reason generating an image that has two or three box art and marquee images for some reason. This is through standard use, I’ve not messed about with the settings (I’m aware you can customise the screenshot settings, but I’ve left is as default).

**Comment by muldjord** [comment]
Please be more specific. Provide examples. I don't understand what you mean by "The scraper is for some reason generating an image that has two or three box art and marquee images for some reason".

**Comment by muldjord** [comment]
I have one thing that could cause this. If you've created a game list using Skyscraper at some point, and then reimported them using the "esgamelist" module, then you will get this result which is expected since it then re-imports the screenshots back into the cache and then re-composites them back again. If this is the case then this is something you need to be aware of yourself. This is not an error with Skyscraper.

**Comment by trevor7oaks** [comment]
My error then. I had assumed the esgamelist replaces the localdb as a source. I used to use each source and then local and that combined the results

**Comment by trevor7oaks** [comment]
Would the solution be to purge the cache and scrape again, this time not gathering from esgamelist?

**Comment by muldjord** [comment]
I would simply purge all of the screenshots from the esgamelist source, which is probably the only media that is faulty:
```
$ Skyscraper -p <PLATFORM> --cache purge:m=esgamelist,t=screenshot
```
Then regenerate the game list with:
```
$ Skyscraper -p <PLATFORM>
```
EDIT: Just a quick note: You very rarely need to purge your entire cache. There's a lot of valuable information in there. So it is almost always best to only purge the media that is giving you issues. Otherwise you'll have to scrape everything all over again from all sources.

**Comment by trevor7oaks** [comment]
Thanks Lars. I purged the data from the three systems and went again. First system scraped and worked perfectly.  Screen scraper is struggling to find data for the next, perhaps I’ve used it too much today, not sure if there’s a limit. Or it’s in high use.

Thanks again for an awesome scraper 👍🏻

Trevor
