### ISSUE TITLE
Failed and Aborted Install

### ISSUE THREAD

**Issue by hcasey** [muldjord/skyscraper#143]
After updating the install script, installing skyscraper, choosing the emulators to scrape, scraping and building the gamelist, on reboot, the pi locks up and leaves the following error message: 

emulationstation: /home/pi/RetroPie-Setup/tmp/build/emulationstation/es-app/src/FileData.cpp:216: void FileData::addChild(FileData*): Assertion `mType ==FOLDER' failed. Aborted

The screen stops at the terminal screen at the pi@retropie:~ $ prompt with a blinking prompt.
It won't respond to any keyboard commands.

I've installed it on a 3B with a 64GB chip, RetroPie 4.4 and a 3B+ with a 124GB chip also with RetroPie 4.4. Both installs use mostly the same emulators and game files.

I'm installing skyscraper in an arcade cabinet using old school buttons and joysticks. I have added specialty buttons for save states, volume controls and menu calls. To do this, I'm using the ipac ultimate board using keyboard mode and I've manually edited the retroarch.cfg file to organize it and delete features not used (16 player functions, online functions, and fastforward or other features that conflict with 2 player or mame features.

**Technical information**
 - Skyscraper version: not sure
 - Internet connection: wifi
 - OS: RetroPie
 - OS Version: 4.4
 - Hardware: RaspberryPi 3B and 3B+
 - Chip: Samsung 64 and 128GB

I hope this is enough information. I really like what I've seen about skyscraper and want it for these two builds.

**Comment by muldjord** [comment]
Have you tried this on a fresh install? I'm not convinced this is a Skyscraper error. Mostly because I've never seen or heard about this particular error before, and the only thing Skyscraper does in relation to ES is write the gamelist.xml files. And in the case of gamelist.xml errors it usually just tells you that there is an error and then just doesn't load that gamelist.xml file, but still proceeds. If this happened after updating the system and you then used Skyscraper before rebooting, it is much more likely that it was the general update that broke your system and it is a case of "now this doesn't work and the last thing I did was Skyscraper, so it must be Skyscraper causing the trouble" when in fact it could be that ES was updated and that was what broke it. Just a thought you'd need to consider.

What you can try:
My suggestion is to try and move ALL of the gamelist.xml files you've generated using Skyscraper somewhere else, and then try to reboot the system and then see if it works again. In that case it could be related to one of the gamelist.xml files and / or the artwork related to it. I'd need you to then put one gamelist.xml file back at a time until it stops working again. And then I'd need you to put the faulty gamelist.xml somewhere I can get it so I can debug the problem with it.

**Comment by hcasey** [comment]
Both installations were fresh installs.
In both cases, the computer, or the chip specifically, becomes un-bootable.
I'll try and re-write the disk image and remove all of the gamelist.xml files and artwork before trying again.

**Comment by muldjord** [comment]
Closing from lack of response. Let me know if you find evidence that this is Skyscraper related.
