### ISSUE TITLE
Preserve original image compression type

### ISSUE THREAD

**Issue by kcgen** [muldjord/skyscraper#155]
I noticed much of my scraped cover art and screenshots contain what appears to be jpeg compression artifacts despite the image format being PNG.

After some digging, I realized Skyscraper always transcodes JPEG images to PNG format (similar to transcoding an MP3 into FLAC format).  This results in a significant space cost with zero benefit in image quality. 

For example, this cover art https://www.mobygames.com/images/covers/l/78400-superman-nes-front-cover.jpg is 169KB, but when Skyscraper re-encodes it as a PNG the size baloons to 800KB which uses 4.7x disk space.

Is it possible for Skyscraper to cache and operate on files in their native image format, be it JPEG or PNG? Rendering the combined cover+screenshot+marque could still be a PNG, but atleast all of the source assets would be saved in their native formats resulting in a huge space savings.
This would also significantly reduces the space savings when writing the media/ folder to retropie, where SD-card space is at a premium.

**Comment by muldjord** [comment]
Oh boy, there's many aspects to this to discuss. I agree with your assessments. Converting to PNG does not provide a gain if the original sizes were kept (using `--noresize`) - but this is not the default behaviour of Skyscraper.
I downsize large artwork, especially important for the cover artworks as they are often very high res. Hi-res makes sense if you want to print your own cover on physical paper. But for Skyscraper's purposes they are overkill and makes the artwork composition stage slow.
So I could resize the JPEG and then save it as JPEG again. But that would mean more artifacts than the original, which is bad since they are still downscaled. So I go with lossless 24bit PNG's to ensure the highest quality of the end-product in the frontend. And that's across the board for all types. I need to keep this as close to the original as possible but still resize it for speed. It's basically as simple as that.

If you want to get as close to the original artwork as possible, you can use the `--noresize` option on command line or the `noResize=true` set in config.ini. This will force Skyscraper to never resize the incoming artwork. Just keep in mind that this will save all artwork in its original size, which is quite insane for cover artwork, as they are often scanned in 300dpi or above. So you'll run out of diskspace real quick. And they are still converted to lossless 24bit PNG's.

I will consider a `--noconvert` option or similar that would never resize and just keep the originals of everything, at the cost of speed while generating gamelists.

**Comment by kcgen** [comment]
Indeed - makes perfect sense to always resize to lossless.  
That would be fantastic if `--noresize` downloaded art in its native format (and only switch formats to PNG when compositing / combining images). 

I've used --noresize exclusively since starting to use Skyscraper, and performance is excellent. The screen is a blur of when generating the final gamelist for 1,000 roms; roughly 20 seconds on an i7-6700k + SSD.

I enjoy seeing the 3-second full-resolution cover-art just after I launch a game in RetroPie.  To do this, place the full-res cover art in: ` <rom-folder>/images/<name_of_rom>-image.png`.  The full resolution really does look great, as most displays are 1080p. 

See here: https://github.com/RetroPie/RetroPie-Setup/blob/c8f6cfdf3ec9a3aa8c2260bca7f1807a26b55e12/scriptmodules/supplementary/runcommand/runcommand.sh#L911

RetroPie's "Launch Menu Art" needs to be enabled as well, which sets the USE_ART=1 variable:
https://github.com/RetroPie/RetroPie-Setup/wiki/runcommand#configuring-runcommand

Most cover art is actually no larger than 1920x1080 (much of it is just a bit under 720p). I'lll gather some statistics from my 18GB worth of ~/.skyscraper/cache/*/covers/*:

Number of covers: 27,288

**Width:** 
```
Min        Max      Median        Avg     Stddev
 93       4288         512     569.19     212.01
```
**Height:**
```
Min        Max      Median        Avg     Stddev
119       4096         620     678.32     296.91
```

**Comment by muldjord** [comment]
I think you are right, this would make sense to incorporate as the default behaviour of `--noresize`. I was also thinking of using it by default, period. But that introduces an old problem I had. When generating the gamelists a LOT of images are loaded into ram, which was part of the reason for resizing them. If more of the threads load a huge cover at the same time (and they will) it will run out of memory on the pi and Skyscraper will crash.

So it makes sense for the `--noresize` option for this to be default as the problem already exists here and it's a forced behaviour from the user (meaning they hopefully have a better understanding of what they are doing).

Either way, I like the idea and will consider how to best implement this. Now there's just the question of having the time and energy to do so... :D

**Comment by kcgen** [comment]
Excellent, and thank you!

**Comment by muldjord** [comment]
So, it took a while, but I've now implemented this. Basically I've decided to deprecate the `--noresize` option and `cacheResize` config.ini option altogether and make this the default behaviour. This means that Skyscraper, from 3.4.0 and forward, will always keep the image data intact as it was delivered directly by the sources.

EDIT: There is a caveat in speed and memory use though. So I hope this doesn't make things crash for some people. I will do a bunch of testing to see what impact this actually has.

**Comment by kcgen** [comment]
Thank you @muldjord ! 
I'm looking forward to re-generating with 3.4.0!

**Comment by muldjord** [comment]
I've expanded this quite a bit now. `--noresize` is now required again, which will save the images using the original format and size (completely untouched). I had to reintroduce `--noresize` since some images took up to 3 megabytes or more, which is just bonkers.

I've also made the default behaviour (resize) quite a lot more intelligent. It will now check for an alpha channel and whether it is actually used. If it is, it will resize and save as PNG. If no alpha channel is used, it will save as JPG with configurable quality (95 is default, which is almost as good as a PNG, but a factor 5 smaller in size). This will save a lot of space and should be high enough quality that no-one will notice it.

**Comment by muldjord** [comment]
Also, I've been a bit conflicted on whether noresize should be default. But I've concluded that the majority of the Skyscraper users will not want or need the originals and will be glad to save the space. Having even a few 4000x3000 covers lying around is pretty silly if you ask me. And screenscraper even often, if not almost always, delivers those hires covers in PNG(!).

But as I said, I will do some comparisons of disk usage with and without noresize when I'm completely satisfied with the implementation. The disk space saved when resizing should be quite significant and, to most users, unnoticable when generating the gamelists.

**Comment by muldjord** [comment]
Results are in:
```
Mastersystem with 29 roms
screenscraper:
noresize
29.1 MB
resized
7.7 MB

thegamesdb:
noresize
12.7 MB
resized
2.9 MB
```

**Comment by muldjord** [comment]
I also did some comparisons with the default artwork exported from Skyscraper. I can't tell the difference (even when zooming in) between the ones generated from resized and non-resized cache. So that's pretty cool.

Anyways, sorry for yabbing on in here, I'm kind of using it to document my progress now as well, so others can see it.

**Comment by muldjord** [comment]
Changed default jpgQuality to 95 after some further tests. This is a win-win for everyone basically. Using this new method I now save all images in larger sizes than default for 3.3.8, but with less disk space requirements and almost the same quality. And `--noresize` is now much more usable for those who require it since resources recieved as JPG will automatically be saved as that, untouched. So no more insane sized PNG's when using `--noresize`.

**Comment by kcgen** [comment]
@muldjord , win-win indeed -- both options are going to save a lot of storage versus prior behavior. :+1:

**Comment by muldjord** [comment]
3.4.0 now released, thanks for your suggestion. Closing, let me know if you have issues.

**Comment by kcgen** [comment]
Thank you @muldjord ; will report back any issues.
