### ISSUE TITLE
Support for Pegasus frontend

### ISSUE THREAD

**Issue by igno2k** [muldjord/skyscraper#156]
Is it possible to include support for the Pegasus frontend? It is actively developed and becoming more and more popular.

Here you can find a reference guide the the meta file format:
https://pegasus-frontend.org/docs/user-guide/meta-files/

At the moment I am using skyscraper with Emulationstation format as output and converting it online via https://pegasus-frontend.org/tools/convert/

Would be really happy to see this addition! And thanks for your great work :)

**Comment by muldjord** [comment]
Yes, I would like to add support for Pegasus. Shouldn't be too hard to do as it seems quite well-documented.

**Comment by igno2k** [comment]
Perfect, thank you!

If you need somebody to test the implementation I am willing to help!

**Comment by muldjord** [comment]
That would be great. I am almost done with it actually, so I'll let you know when it's ready for testing.

**Comment by igno2k** [comment]
Great - at the moment I am on holidays so I can test it by the end of this week

**Comment by muldjord** [comment]
Shaping up nicely: [https://youtu.be/cuHM3FKYtqw](https://youtu.be/cuHM3FKYtqw)

**Comment by igno2k** [comment]
Nice!

Can‘t wait to test it with my favorite theme [gameOS](https://github.com/PlayingKarrde/gameOS)

**Comment by muldjord** [comment]
Skyscraper 3.2.3 now released with Pegasus support implemented. :) Please read the details here: https://retropie.org.uk/forum/topic/11826/versatile-c-game-scraper-skyscraper/1235

**Comment by igno2k** [comment]
Perfect - thank you!

**Comment by DryKillLogic** [comment]
thanks @muldjord!. Is it possible to generate the assets needed for https://github.com/PlayingKarrde/gameOS?.

**Comment by muldjord** [comment]
This is something you should do yourself, it is already able to do it with the right artwork configuration. Please check here: https://github.com/muldjord/skyscraper/blob/master/docs/ARTWORK.md

**Comment by DryKillLogic** [comment]
Thanks for the quick answer Lars!. 

My understanding is that skyscraper supports four asset types only (marquee, wheel, cover, and screenshot) and those can be customized through artwork.xml but there's no functionality to add an additional type/custom type even if Screenscraper API supports it.

At the beginning, I thought that was the skraper.net approach but I realized it's already built-in after I checked a PDF file included in the package that talks about it.

Since the gameOS theme is using the "box2dfront" and "fanart" assets, I don't think it's possible to fetch all the resources needed with skyscraper. 

<img width="497" alt="Screen Shot 2019-10-01 at 7 17 01 PM" src="https://user-images.githubusercontent.com/2207122/66013443-13c2ef80-e480-11e9-87a1-982efb8ebea7.png">

Please correct me if I got something wrong, and I'm sorry for the lack of details on my previous question.

**Comment by muldjord** [comment]
I think for pegasus I made it so "box2dfront" is "cover". But I can't remember.

**Comment by DryKillLogic** [comment]
Cool, so it would be a matter of renaming the folder for that one. 
I think it would be a very useful feature to pass what types/resources need to be fetched (and keep the existing four as default values). I'm not sure how hard that might be though.

Thanks!.

**Comment by Sixdd6** [comment]
I've got a request if it isn't already set this way. When exporting game list for pegasus, passing the -e flag should allow to set the launch paramater for the platform. Also allowing to set this in the config per platform would be awesome too.

**Comment by muldjord** [comment]
I've added this functionality. It can now be used to set the launch parameter for the Pegasus frontend. It will be in the next release, no ETA. :) Thanks for suggesting this.

**Comment by Sixdd6** [comment]
Awesome, can't wait to use it. 😃
