### ISSUE TITLE
Update docs for Windows Subsystem for Linux

### ISSUE THREAD

**Issue by Keithcat767** [muldjord/skyscraper#159]
Hello!

Just wanted to post here that this works great using Windows Subsystem for Linux. A couple gotchas:

You need to install build-essential to compile: `apt-get install build-essential`
Also, the file paths are a bit funky using the subsystem. You need to create the folder by accessing `/mnt/c` and be explicit with your file paths.

All that said, I would be happy to provide a PR with some updated documentation on how to get this working on windows. It was pretty straight forward and it is working great!

Let me know your thoughts! Thanks for the awesome tool!

**Comment by muldjord** [comment]
It actually compiles natively under Windows, so you can just download Qt and compile it as any other Qt program. The downside to that the terminal output is a bit weird because of the very basic command prompt terminal in Windows. You might even get it to work with Powershell (I haven't tried).

As for documentation for getting this to work with the WSL I think I would want it in a subdocument to the README. So if you could create it as a document named something like "docs/INSTALL_WSL.md" and create a PR for that when it's fully documented, I can pull that in. Thanks!
