### ISSUE TITLE
Cover art left blank in metadata files

### ISSUE THREAD

**Issue by ryanc919** [muldjord/skyscraper#161]
I'm using the latest Skyscraper build on Mac OS and I have it writing metadata files for Emulation Station and Pegasus, but for each metadata file it is leaving the field for cover art blank. This is despite the fact I can see those assets in the db.xml file. 

I'm using the Pegasus frontend on my Mac and the result is that my games list appears as plane lines of text rather than showing as icons of box art. It should be writing a "assets.boxFront: 'path to artwork'" line should it not? Is this normal behavior or do I have to manually add the cover art lines to the Pegasus metadata file?

**Comment by muldjord** [comment]
This is not a bug, but rather because your artwork.xml is not set up to look good with Pegasus. The default artwork.xml is made to look good with EmulationStation. You can basically set it up any way you like, but here's my suggestion for a good Pegasus look:
```
<?xml version="1.0" encoding="UTF-8"?>
<artwork>
  <output type="screenshot" width="640"/>
  <output type="cover" width="640" height="480">
    <layer resource="cover" height="480" align="center" valign="middle">
      <gamebox side="wheel" rotate="90"/>
    </layer>
  </output>
  <output type="wheel" height="200"/>
</artwork>
```
Put this in the `~/.skyscraper/artwork.xml` file and regenerate the game list with `Skyscraper -p <PLATFORM> -f pegasus`.

I'll leave this open for others to see. I actually anticipated this problem since most people don't seem to be aware how powerful Skyscraper's compositor is. You can do [pretty much anything](https://github.com/muldjord/skyscraper/blob/master/docs/ARTWORK.md) with it.

I might look into making default artwork.xml files for each frontend in future releases.

**Comment by ryanc919** [comment]
I appreciate how powerful it is, and your suggestion worked perfectly. Love it!
