### ISSUE TITLE
.cue vs .img psx

### ISSUE THREAD

**Issue by JHale716** [muldjord/skyscraper#168]
This may or may not be an issue. Haven't located any comments on it. When scraping psx the scraper inconsistently matches to .img or .cue filenames. The emulator I'm using, Mednafen, uses .cue files and not the .img files. As a result, scraped results matched to the .img file don't launch properly and the launchable .cue file doesn't have scraper data.

And there is the issue of the duplicate entry in the emulation station menus.

Have worked around by find/replace .img to .cue in the gameslist.xml file for psx. 

Running on macmini C2D hardware, with Linux mint tara 19. Custom build Emmulationstation frontend.

**Comment by muldjord** [comment]
Usually .cue files are describing data in a .bin file. I have never seen them combined with an .img file before. The problem here is that Skyscraper accepts both .cue *and* .img files for the psx platform. So therefore it will try to scrape both. Since .img files can stand by themselves this is how it has to be. For your specific case, you can override the file extension for the psx platform by setting it in `~/.skyscraper/config.ini` as described [here](https://github.com/muldjord/skyscraper/blob/master/docs/CONFIGINI.md#extensionszip-uae-adf)

**Comment by JHale716** [comment]
Thanks!

I'll give it a shot. Interesting that the emulator won't run the img files

Cheers

J-P
p.s. Book a meeting in my calendar

ph. 09 215 8998 | m. 021 022 69 127

**Comment by muldjord** [comment]
I'm thinking that maybe they are actually .bin files that someone renamed to .img. As mentioned I've never seen .cue files paired with .img files before.

**Comment by JHale716** [comment]
Interesting.

I’m new to emulation games but been in IT since the 90’s

The roms are from planetemu.net and they come in a .zip with .ccd, .cue, .img, and .sub files

looking at it from my mac using winzip it lists the files as
.ccd Document
.cue CUE file
.img Classic Disk Image
.sub Subtitle File

The mednafen emulator won’t run them zipped, so I have unzipped them into the roms folder that is being scrapped. And the emulator only runs .cue and .m3u files. .m3u as I understand is used where multiple image files are used.

Reading the gametechwiki, the .m3u files reference the .cue files for multiple disc requirements. Never the binary…


Cheers

J-P
p.s. Book a meeting in my calendar

ph. 09 215 8998 | m. 021 022 69 127

**Comment by muldjord** [comment]
That is correct. m3u->cue->bin is usually how it goes. And the .cue file defines the tracks inside the accompanying .bin file. It's not specific to emulators though, this is how that type of disc image works in general. And it has always been a pairing of a .cue file with an .img file. So that leads me to believe someone renamed the .bin file to a .img file. I'm guessing you can just rename them back to .bin and edit the .cue file to reflect that and it will probably work just fine.

Quick note: I've redacted the url in your previous post as I want to avoid direct links to rom related sites.

**Comment by JHale716** [comment]
Thanks for that. Sorry wasn't aware this was posting to the git thread...

Replying by email 🤷‍♂️🤦‍♂️😂

Cheers

J-P
p.s. Book a meeting in my calendar

ph. 09 215 8998 | m. 021 022 69 127
