### ISSUE TITLE
add PS3 to platform.cpp

### ISSUE THREAD

**Issue by zosky** [muldjord/skyscraper#169]
hi. looks like ps3 is already in [thegamesdb.cpp#L358](
 https://github.com/muldjord/skyscraper/blob/master/src/thegamesdb.cpp#L358) and it works pretty well
```
Average search match: 98%
Average entry completeness: 57%

Total number of games: 117
Successfully processed games: 116
```
**first** i had to add ps3 in [platform.cpp](https://github.com/muldjord/skyscraper/blob/master/src/platform.cpp) ... by duplicate the ps2 lines

is more required when adding new platforms ? would you like to see a pull request ?

**Comment by muldjord** [comment]
Yes, more needs to be done, but no need for a pull request, I will add it. :)

EDIT: One question: What file extensions do the rpcs3 use? I can't find documentation for that.

**Comment by zosky** [comment]
havn't tried rpcs3 - i just got my hands on a _real one_ so im using ss to make a front-end for the real thing. 

their [quickStart](https://rpcs3.net/quickstart) guide isn't very clear; here's what i found
- disk backup ( .**iso** ) can be anywhere, started from > file > boot game
- psn apps ( .**pkg** ) must be installed > file > install pkg 

installed apps & games make a folder ~/.config/rpcs3/dev_hdd0/game/**[game-id]** like BLUS30443 or NPEB01393. 

~~also, it feels like thegamesdb is light on PSN titles, i've only scraped disks at the moment.~~
UPDATE: i added .pkg and scrapped again ... most where picked up. the few it missed are in gamesDB but only for other platforms

```
Average search match: 97%
Average entry completeness: 56%

Total number of games: 171
Successfully processed games: 157
Skipped games: 14
```

**Comment by CookiePLMonster** [comment]
I'll bump this topic with an answer, since I looked up to see if somebody's brought the topic of adding PS3/X360 platforms and found this issue:

> EDIT: One question: What file extensions do the rpcs3 use? I can't find documentation for that.

RPCS3 is unlike emulators for other platforms where you run games by pointing to their ISO files - granted, for disc games it still kind of is like that, but PSN games get installed in RPCS3 same way they are on real console. I would say extension detection will not really work for platforms like this - and it should be handled more like Moonlight streaming.

**Comment by muldjord** [comment]
Thanks. I do feel like the usefulness of adding ps3 and xb360 is pretty limited, so I'm kind of leaning towards not adding them. I don't want to add something just for the heck of it. It bloats the software and I am strongly against that. Skyscraper is a retro scraper after all.

I'm personally of the opinion that anything newer than Dreamcast makes little sense due to how the newer consoles are so bound to accounts and other online services.

**Comment by CookiePLMonster** [comment]
> It bloats the software and I am strongly against that. Skyscraper is a retro scraper after all.

If I recall correctly, adding a new platform was as easy as adding new if clauses in 3-4 functions - if that contributes to "making the software bloated" maybe the problem lies in how those platforms are added and managed, and not in the fact they are being added.

I don't disagree with you on Skyscraper being a retro scraper, but there is still some use in scraping those for the sake of streaming.

**Comment by zkvsky** [comment]
@muldjord 
While I'd agree with your assessment of the emulators past 7th generation of consoles, I'd have to add that it's not as clear cut. We have amazingly emulated WiiU and two competing Switch emus, which are getting there at breakneck speed.
RPCS3, while itss file organization is a mess, reflecting consoles filesystem [ rom detection would be an issue I guess? ] it has some extremely popular exclusive titles which are perfectly playable even on puny APU. Situation with Xbox is similar but emus are far worse.
Another thing is that so far it's quite launcher unfriendly [ all above-mentioned are ], it doesn't have gui-less direct game launch option and just recently I've seen commits around that.
I don't really understand the online bound accounts argument but my feeling is probably similar to your consensus "not for now"
RPCS3 has open plans for a RetrArch core, so far nobody picked it up, core would be a clear indication that it's mature enough for addition into SkyScraper I'd guess

**Comment by muldjord** [comment]
@CookiePLMonster I am not talking about bloating the codebase. Skyscraper is designed in a way that I can easily add platforms, as you describe yourself, although not as simple as you point out as some modules require platform id's added as well.
But if you knew how many obscure platforms I've been asked to add over the course of Skyscraper's life, you'd probably understand why I am inquisitive about adding any platforms at all.

I am not against adding platforms, but I certainly reserve the right to ask questions and decide for- and against them.

**Comment by muldjord** [comment]
@barolo I agree. It's more of a rule of thumb for me until the contrary has been presented in a way I think makes sense. I am aware of the WiiU emulators and such, and Skyscraper already supports Wii.

But let's not make this a discussion about x or y platforms. This request is about the ps3 platform in particular.

And for Skyscraper, I'd need specific file extensions to look for. It's really quite simple. So far I haven't had a clear answer for this and therefore cannot add 'ps3'. `*.iso` and `*.pkg` seem to be relevant, but I'm sure there must be more.

**Comment by mrsilver76** [comment]
Two years later, is there any chance this could be reconsidered?

I can confirm that the specific extensions for RPCS3 should be `*.iso` and `*.pkg`.
