### ISSUE TITLE
Don't give up so easily when using --unattendskip

### ISSUE THREAD

**Issue by HumanRob** [muldjord/skyscraper#172]
**Describe the feature**
After I add a some roms to an existing system I like to use Skyscraper to get their videos and screenshots. I use --unattendskip to ignore existing entries. I've noticed on systems when I have lots of existing unmatched roms (usually things like rom hacks where I wouldn't expect many matches) it will give up after 42 tries without finding any matches. However in this case it makes sense for there not be many matches as most of the missing items are things I wouldn't expect many matches for (rom hacks) so I would prefer it carries on to get to my newly added roms without giving up.
Do you think it would make sense to only have the 'I give up' feature when we're not skipping existing entries? 

If you don't agree with this, or if I'm doing something wrong (maybe there's a better way to only scrape new roms?) feel free to delete this. 

Thanks!

**Comment by muldjord** [comment]
EDIT: I just figured out what you mean by the `--unattendskip` option (I don't use this option myself so I just had to think it through in my mind to understand your issue). Since you have many rom hacks "not found" roms will built up over time. So when you are using `--unattendskip` it will skip directly to the same "not found" roms every time. This is not usually a problem when not using that option as the cached roms will also be looked up from the cache and be "found".

The limit of 42 "not found" is there to ensure that the sources aren't hammered too hard in case people try to scrape platforms with a scraping module that doesn't support it. So that's the explanation for the limit.

Fix 1: And now for the fix. Skyscraper allows you to extend this limit up to 200. Check the docs [here](https://github.com/muldjord/skyscraper/blob/master/docs/CONFIGINI.md#maxfails30).

Fix 2: Make sure your rom hacks have data, either by using the `-s import` module or by using the `--cache edit` option. [Check the docs](https://github.com/muldjord/skyscraper/tree/master/docs) for more info.

Good luck! I'm gonna close this. :)
