### ISSUE TITLE
Media placement - Simple Mode

### ISSUE THREAD

**Issue by slappymcphee** [muldjord/skyscraper#18]
Ok, so I get that this is mainly for the Raspberry Pi with RetroPie build on Debian however we are seeing an issue that may be OS related however I am not so sure. First of all the installation instance is on an Odroid XU4 with Ubuntu Minimal 16.04LTS.  We use a path of `/home/pigaming` rather than `/home/pi/` since this is not a raspberry pi board.  It appears that the covers and wheels  and even in some instances videos that skyscraper scrapes are winding up in the ` /home/pigaming/.skyscraper/dbs` folder and never making in into the game list prescribed folder. This is a issue not only because it takes up space and people wont know why they have no space left, but also my understanding is that the application is not meant to have the media removed from the db.  I am at a loss if during the "wizard" I tell it where to dump the media that the path being provided is being ignored. I also just want to add that I know there are some kinks to work out with this but it is the best scraper I've seen so far. The XMLs it produces are gold and the application seems like it is becoming very stable and overall for the most part reliable.

**Comment by muldjord** [comment]
The media in the dbs folder is the cached data and is supposed to be there. Don't touch that unless you want to delete the cached data.

Please post the contents of /home/pigaming/.skyscraper/skyscript.sh here so I can check what you have done.

**Comment by muldjord** [comment]
Let me just point out that It makes no difference if your home folder is 'pi' or 'pigaming'. Skyscraper does not have a hardcoded home folder, but instead uses a dynamic one, which in your case is '/home/pigaming'. This clearly works since the Skyscraper data files have been correctly installed to '/home/pigaming/.skyscraper'.

So if you have your roms in /home/pigaming/RetroPie/roms/[platform], then you don't even need to provide your own input path or game list path or any of the other paths. It should just work with defaults.

**Comment by muldjord** [comment]
Just tested Simple Mode and it works just fine with custom folders on an Ubuntu system, closing issue.

Please comment with contents of /home/pigaming/.skyscraper/skyscript.sh so I can figure out what you are doing wrong.

**Comment by Jmanning6600** [comment]
Why would you close this issue we are telling you we are having the issue. I have scraped multiple systems set the default folders for everything and have never gotten marquees or covers to show up in the pigaming roms folder. Could it be possible there is some kind of incompatibility issue with the odroid. Simple mode is pretty simple and im telling you this issue is real and remains unresolved. They do however show up in the dbs folder. Also neither wheels or marquees are written in the xml.

**Comment by Jmanning6600** [comment]
[skyscript.zip](https://github.com/muldjord/skyscraper/files/1834572/skyscript.zip)

**Comment by Jmanning6600** [comment]
Ok i just did a fresh install of our image scraped 1 system wheels and covers did not show in the folders

**Comment by muldjord** [comment]
I just tested it here, on a Ubuntu system, and it works just fine. I've tested all custom folders and it gets exported exactly as it is supposed to when setting them in Simple Mode. So please tell me, what else do I need to do then?

Your skyscript.sh file looks fine aswell.

Maybe you have permission issues with your folders not allowing Skyscraper to save its files. I don't know, and I can't help you with this since it is not Skyscraper related.

**Comment by muldjord** [comment]
Btw, you DO NOT need to set custom folders at all. Since you have your files in the same place as the RetroPie platform, Skyscraper will work with defaults.

**Comment by Jmanning6600** [comment]
we have tested this and i did not work we had to make a custom config ini for it to start working.
[config.zip](https://github.com/muldjord/skyscraper/files/1834661/config.zip)

**Comment by Jmanning6600** [comment]
Also the folder we have it in has a different name from retro pie.

**Comment by muldjord** [comment]
Oh, in that case, yes, then you need them. At least for the ones you've changed. But for the rest, it is not necessary and is most likely because Skyscraper isn't allowed to save files in the folders.

**Comment by Jmanning6600** [comment]
OK then so this is very informative then. We don't want to be a bother to you but this is why we ask questions. I for one think your program is great and we just want to share it with the rest of the community. I hope you don't see this as us pestering. We are just trying to learn so we can put it out fully functional and you don't have a bunch of question from people after using it with the odr
oid. We will look into this permissions thing. and thanks again for the info.

**Comment by muldjord** [comment]
Oh for f's sake, I just realized what is going on... You do not have a permission problem. Please read the artwork documentation: https://github.com/muldjord/skyscraper/blob/master/ARTWORK.md

What is happening is that you are looking to export the raw cover, screenshot and marquee's. As the documentation states, that is not the default behaviour of Skyscraper. It only exports the screenshot composited of cover, screenshot and wheel. That is the most powerful part of Skyscraper. It allows you to export media exactly as you want. It will take me too long to explain here, so please read the link above thoroughly.

**Comment by muldjord** [comment]
I would like to point you to /home/pigaming/.skyscraper/artwork.xml

That is the file you need to edit.

**Comment by Jmanning6600** [comment]
Ok but what about the config.ini it does not work without it do you think that is a permissions problem?

**Comment by muldjord** [comment]
No, no permission problems. The config.ini is just fine if you just define the platforms you have renamed.

**Comment by muldjord** [comment]
Well, yes, but that would completely go against the design of Skyscraper. You can disable local caching with --nolocaldb, but that would break Simple Mode completely since it makes heavy use of the cached data throughout the localdb run.
The local database cache is there to make sure you can always rescrape a platform quickly and without putting load on the game database sources.

If what you are looking for is a simpler scraper that just scrapes the resources I would suggest using SSelphs scraper instead. I haven't used it for a long time, but I seem to recall it doing just that, without caching data.

**Comment by Jmanning6600** [comment]
Yea ill pass on the sselphs scraper i like yours better. But thank you for the education. have a good day.
