### ISSUE TITLE
"ScreenScraper APIv2 returned invalid / empty Json"

### ISSUE THREAD

**Issue by GiulioCentorame** [muldjord/skyscraper#186]
**Describe the bug**
Skyscraper skipped several games while scraping with Screenscraper.fr, displaying the error "ScreenScraper APIv2 returned invalid / empty Json". Output: [screenscraper_error.json.txt](https://github.com/muldjord/skyscraper/files/4022277/screenscraper_error.json.txt)

**To Reproduce**
Run Skyscraper from RetroPie-Setup. I left all the default values untouched.

**Special circumstances**
I am using a CRTPi build on my SD card.

**Terminal output**
I completely forgot to copy and paste it, but it was all handled by the script, mentioning to file a bug report for it and the location of the json. Let me know if you need it.

**Technical information**
 - Skyscraper version: 3.3.5
 - Internet connection: wifi
 - OS: CRTPi (RetroPie custom build)
 - OS Version 1.0 (Composite fork)

**Additional context**
I was having several empty results before, so I updated the script to the latest version and quit RetroPie-Setup.

**Comment by muldjord** [comment]
This is due to the limits in their API. Thank you for reporting it though as I haven't seen this way of handling too many threads before from their API. You can get a more stable use of it by registering a user at their site and using the user credentials with Skyscraper by setting it in Skyscraper's config.ini with:
```
[screenscraper]
userCreds="USER:PASS"
```
EDIT: The error message from the json output you uploaded will now give a proper error in the output from 3.3.6 (still unreleased).

**Comment by GiulioCentorame** [comment]
Thank you. I am currently experiencing no errors as a registered user.
