### ISSUE TITLE
Stretch version for pi 3 model b+

### ISSUE THREAD

**Issue by drewcsontos** [muldjord/skyscraper#19]
Please make a version for the stretch beta version of RetroPie. It will install, but when I type in Skyscraper in both the regular directory and skysource, it says command not found.

**Comment by muldjord** [comment]
I already tested it on the stretch image, and it works fine. Please re-try the installation procedure and if you run into problems, be as specific as to where it fails as possible. Thank you. :)

**Comment by drewcsontos** [comment]
Thank you, I’ll try again tonight. The problem was that when I typed in the command “Skyscraper”, it said command not found, even though it said earlier that skyscraper was up to date.

**Comment by muldjord** [comment]
That's probably because the final "sudo make install" step has failed, potentially from a wrongly typed sudo password. I should probably do a check for that.

You should just be able to do the following then, so you don't have to compile it all over:
1. cd
2. cd skysource
3. sudo make install
4. Type in your sudo password very carefully (default is 'raspberry')

Let me know how that goes.

**Comment by muldjord** [comment]
Any update on this? Otherwise I'm gonna close it.

**Comment by drewcsontos** [comment]
You can close it. It works now. Thanks for your help!
