### ISSUE TITLE
Can't scrape PC Engine CD games?

### ISSUE THREAD

**Issue by joaoluizcarvalho** [muldjord/skyscraper#199]
My pcengine roms folder has hucard games (*.pce, zipped) and one CD game (cue+bin, not zipped). I was able to scrape the hucard games just fine, but the I added this one CD game and Skyscraper doesn't seem to be recognizing the cue+bin format as valid for this platform. The game plays fine, but Skyscraper says there are zero new games in the platform's rom folder and doesn't even try to scrape.

I tried adding the lines below to my config.ini file, but it still did not work:
[pcengine]
addExtensions="*.cue"

Got any advice? Thank you!

**Comment by muldjord** [comment]
It already supports `.cue` files for the `pcengine` platform. If it doesn't find data for the file, it is because the source doesn't recognize your ISO. I just tested with an empty `blah.cue` file and it processes it just fine (although it doesn't find any data for it of course), so it's hard for me to figure out what is wrong on your end. Maybe the file is calle `.CUE` instead of `.cue` or something? Or maybe it has an empty entry in the gamelist and you are asking it to skip it.

**Comment by joaoluizcarvalho** [comment]
Yes, there was an empty entry in the gamelist and I was asking Skyscraper to skip it. I played the game once to test it (before scraping) and retropie automatically added the game to the gamelist. I didn't know it did that. Sorry about that. Removing the gamelist entry solved it. Sorry for wasting your time and thank you for the suggestion.
