### ISSUE TITLE
Amiga games not found when you select no scraper

### ISSUE THREAD

**Issue by MarcoVer77** [muldjord/skyscraper#20]
Hi Lars,

just want to say that in version 2.4.4 if you scrape amiga with “Skyscraper -p amiga” it doesn’t find anything. If you scrape with”Skyscraper -p amiga -s openretro” it works. So i think openretro isn’t the default?

I’m scraping with .lha files. Also some games like Lotus and Lotus2 are not found because of the name of the .lha file i think.

Greetings,
Marco

**Comment by muldjord** [comment]
This is by design and not an error. 'localdb' is the default scraper for all platforms nowadays. You can either scrape 'amiga' with several different scraping modules manually to gather resources into the local database cache and then finish by scraping with just 'Skyscraper -p amiga' or you can use simple mode. Read more about all of this in the documentation. :)

**Comment by muldjord** [comment]
In other words, when you scrape any platform for the first time without choosing a scraping module manually, you are scraping with 'localdb' which at that point is empty for the platform. It won't give you any results until you fill it up with something. :)

**Comment by MarcoVer77** [comment]
Ah, thanks for the info! Still learning to read. :)
