### ISSUE TITLE
Incorrect matches on street fighter variants

### ISSUE THREAD

**Issue by Shawson** [muldjord/skyscraper#21]
Hi- Firstly, Sky Scraper is amazing!  Great for all my platforms especially the Amiga where everything is quite patchy.  Is there a rule to how I name games?  I've several variants of street fighter 2;

SuperStreetFighter2_v1.1_AGA.lha
SuperStreetFighter2DX_v1.1_AGA.lha
SuperStreetFighter2Turbo_v1.1_CD32.lha

But they all get ripped as the same game?  Whats the source data for the rip, so I can check against that and rename my files accordingly?  Thanks

**Comment by muldjord** [comment]
Hmmm, it's a bit tricky I'm afraid. My guess is that they get scraped as such because the source doesn't have the variants, so the closest match is probably Street Fighter 2. When scraping the Amiga platform Skyscraper uses filename matching, which will occasionally return false positives, it can't be avoided even though I do a lot of neat tricks to make it as robust as possible.

You can fiddle around with the '-m' command line option which sets the percentage of how close a match you will accept. So if you set it at '-m 100' it will only accept 100% matches when it compares the filename against the the returned source title. But that will not fix your problem, just make it not detect those at all. So it's a balancing act. I think it's set to 70% or 65% or something per default, which works really well for most situations.

If you want to test out some renaming of the files, you can try searching for the game at openretro.org or thegamesdb.net and match the filenames with the title in those databases. Then rescrape the games with:
$ Skyscraper -p amiga -s [thegamesdb or openretro] --updatedb [filename.lha]
Please check the output of '--help' for more information on all the options available.
And then, if they get found correctly, rescrape the entire amiga platform again using the new data with:
$ Skyscraper -p amiga -s localdb

That's what I would do. If all else fails, you can provide the data yourself with the '-s import' module. That's too much to cover here, so please check the documentation on how to do that.

**Comment by Shawson** [comment]
Renaming of the files did indeed sort this!  Many thanks!
