### ISSUE TITLE
Modified --refresh mode 

### ISSUE THREAD

**Issue by jacrify** [muldjord/skyscraper#218]
**Describe the feature**
When rerunning against an already scraped scraper without --refresh, the default behaviour seems to be to pull all resources only from local cache, as long as only one resource is present. I would like to be able to run and download only missing resources- ie if I am missing a wheel but a new hit on the scraper shows the wheel is now there, it will be downloaded, without downloading the other image of video files from that scraper.

Note that --onlymissing does not do this- it only downloads from scraper when no resources are in cache.

**Additional context**
This request is only to make my life easier to recover from my recent png lib issues, however the use case is pretty universal- go to the scraper and get new resources added since I last ran, and don't download everything again.

**Comment by muldjord** [comment]
The scraping sources are not designed to grab single resources. It's all or nothing for the REST calls (this is not entirely correct, check my edit), and the default behavior is there to avoid overloading their servers. So I'm closing this as this makes little sense in the current world of scrapers and scraping sources simply because neither Skyscraper nor the sources are designed for it.

I will point you to `--cache report:missing=RESOURCE` and subsequently `--fromfile REPORTFILE`. Check both here: https://github.com/muldjord/skyscraper/blob/master/docs/CLIHELP.md

EDIT: It could check for each artwork resource and ignore those it already has, while fetching the rest, but honestly it's a lot of work for little gain so... I'd have to change the design of Skyscraper rather drastically as it's currently designed to either load from cache or from the source. It can't mix. And I'd rather work on something else to be honest. Maybe for 4.0 at some point.
