### ISSUE TITLE
Attract Mode (overview and missing)

### ISSUE THREAD

**Issue by qqplayer** [muldjord/skyscraper#23]
I love this project but I´m missing a couple of things I don´t know how to do:

1 - Using the "Attract Mode" option I see the tool reading game descriptions and it´s appending all of them into the db foder but doesnt create the "romname.cfg" files to use then on the frontend.
Is there any option to do this?

2 - "Attract Mode"  option too , is there any option to append all the missing scrapped roms at the end of the "emulator.txt" .
 I mean it creates a "missing.txt" file but it inst well formatted to be used with attract mode.
So you need to append it manually to the "emulator.txt" , replacing rom extensions and adding tons of  ";"

**Comment by muldjord** [comment]
Glad you like it.

1. Did you remember to define "-f attractmode" and "-e [emulator]" on the command line (or answer the corresponding questions if you are running 'simple mode')? These are needed for the attractmode mode to work. Otherwise it is creating emulation station gamelists.

2. You can use '--skipped' if you want it to include skipped entries. The skipped files are not meant for attractmode.

Hope that helped.

**Comment by muldjord** [comment]
The db.xml is not related. It is used for locally caching data, not for creating the game list for attractmode. I'm not sure what to say. I've used it with attractmode myself and it has worked as expected. Are you running it on RetroPie? That's what it's designed for, and on there it works just fine and creates the cfg as you request.

**Comment by muldjord** [comment]
Ah, I think I understand now. You'll have to excuse me, I don't use attractmode myself, so I have little knowledge of it. No, Skyscraper currently doesn't use the descriptions when using attractmode. I will add it to the roadmap for a future version.

**Comment by muldjord** [comment]
So, I've implemented this on master now. But it is completely untested. Is it possible that you can test it out if I give you a description on how to compile the master branch? It's quite simple. Let me know if you are willing to help out with this.

**Comment by qqplayer** [comment]
I´ll paste an example of a working .cfg file for an Arcade game , "3 Count Bout"

The file should be named:

`3countb.cfg` 

Text inside:

`overview 3 Count Bout is a one-on-one fighting game. Choose from ten wrestlers who have their own power attacks. There are ten rounds in the game, and each one of them has you fighting other wrestlers that are much tougher than the previous ones. You defeat each one by biting, kicking, and performing other moves to the point where their damage meter is empty. But just because it is empty doesn't mean that you win. You have to pin him for the infamous-three count. Also features competitive play and tag match battles.
`

**Comment by muldjord** [comment]
Perfect, that is what I've made. It will update/create the cfg files in a subfolder of the romlists folder which is called the same as the emulator file. Be aware that this requires the romlists folder to be writable by Skyscraper, but it should already be since it saves the romlists in there.

To compile the master branch, enter each of the following commands:
$ cd
$ mkdir skytemp
$ cd skytemp
$ git clone https://github.com/muldjord/skyscraper.git
$ cd skyscraper
$ qmake
$ make
$ sudo make install
The last command will ask for your sudo password and install this master branch version over the old version. After that, you can verify that it went ok with:
$ Skyscraper --help
And check the version number. If it's "2.4.6" it has installed correctly, and you can test it.

Nothing special is needed to enable the creation of the cfg files. It will create one for any game that it finds a description for. Let me know how it goes.

**Comment by muldjord** [comment]
I just did some quick testing myself just by creating the attract mode emulator and romlist folders manually, and it seems to work as you requested. Looking forward to hearing your results.

**Comment by qqplayer** [comment]
Hi again:

I have compiled the last version with your instructions:

> Skyscraper --helpUsage: Skyscraper [options]
----------------------------------
Skyscraper v2.4.6 by Lars Muldjord
----------------------------------
Skyscraper looks for compatible game files in the input directory. It fetches media files and other relevant information for the games. It composites game art from the recipe at '~/.skyscraper/artwork.xml' and lastly builds a game list file for use with the chosen frontend.

Please check the documentation at 'https://github.com/muldjord/skyscraper' for a detailed explanation of all features.

Launching with this command:

> Skyscraper -p 'c64' -i '/home/lubuntu/Escritorio/C64T' -f 'attractmode' -e 'c64' -g '/home/lubuntu/.skyscraper/media/c64' -o '/home/lubuntu/.skyscraper/media/c64/media' -s 'thegamesdb'

`#204/266 (T4) Pass 1 ---- Game 'Alien (Argus Press Software + Mind Games) (Europe)' found! :) ----
Scraper:        thegamesdb
From cache:     NO
Search match:   100 %
Compare title:  'Alien'
Result title:   'Alien' ()
Platform:       'Commodore 64' ()
Release Date:   '1984-01-01' ()
Developer:      'Paul Clansey' ()
Publisher:      'Argus Press Software' ()
Players:        '1' ()
Tags:           'Adventure' ()
Rating (0-1):   '' ()
Cover:          YES ()
Screenshot:     NO ()
Wheel:          NO ()
Marquee:        NO ()

Description: ()
Lovely SID tune and use of the filter effect. One of the earliest tunes I remember using this effect. The next would have to be David Whittaker (Hocus Focus) and Martin Galway (Comic Bakery, Neverending Story). --hbhzth Lemon64.com

Elapsed time: 00:10:08
Estimated time: 00:13:13
`

It only creates a "C64" folder inside  '/home/lubuntu/.skyscraper/media/c64/media' but is empty.
I am missing something?
Thanks.

**Comment by muldjord** [comment]
With that command, it should create the folder: '/home/lubuntu/.skyscraper/media/c64/c64' (notice twice 'c64' since you added that manually to the romlists folder which is set with -g) and put the cfg files in there.

EDIT: I'm curious, why are you setting the folders inside the .skyscraper folder instead of using the default attractmode folders? (.attract/romlists and .attract/emulators). Is it because of the testing?

Lastly, I'm unsure if the ' you put around the options are messing things up. I would not use those unless the option has spaces which would only ever be relevant for folder and filenames.

**Comment by qqplayer** [comment]
Tried with a more simple command:

`Skyscraper -p c64 -s thegamesdb -i /home/lubuntu/Escritorio/C64T -f attractmode -e c64  
------------------------------------------
Running Skyscraper v2.4.6 by Lars Muldjord
------------------------------------------
Looking for emulator cfg file:
Trying '/home/lubuntu/.skyscraper/c64.cfg'... Found!

Platform:           'c64'
Scraper module:     'thegamesdb'
Emulator:           '/home/lubuntu/.skyscraper/c64.cfg'
Input folder:       '/home/lubuntu/Escritorio/C64T'
Game list folder:   '/home/lubuntu/Escritorio/C64T'
Covers folder:      '/home/lubuntu/Escritorio/C64T/media/flyer'
Screenshots folder: '/home/lubuntu/Escritorio/C64T/media/snap'
Wheels folder:      '/home/lubuntu/Escritorio/C64T/media/wheel'
Marquees folder:    '/home/lubuntu/Escritorio/C64T/media/marquee'
Local db folder:    'dbs/c64'

Looking for optional 'priorities.xml' file in local db folder... Found!
Priorities loaded successfully!

Folder '/home/lubuntu/Escritorio/C64T/media/flyer' doesn't exist, trying to create it... Success!

Folder '/home/lubuntu/Escritorio/C64T/media/snap' doesn't exist, trying to create it... Success!

Folder '/home/lubuntu/Escritorio/C64T/media/wheel' doesn't exist, trying to create it... Success!

Folder '/home/lubuntu/Escritorio/C64T/media/marquee' doesn't exist, trying to create it... Success!


Starting scraping run on 26 files using 4 threads.
Sit back, relax and let me do the work! :)`

The reason because a set folders manually is because my attract mode build is running on a w8.1 machine.
So I use skyscrapper on a vmware - lubuntu 17 virtual machine.

**Comment by muldjord** [comment]
Did it work?

**Comment by qqplayer** [comment]
Nop , just create the "folder" but not the .cfg files.
Could be a C64 only issue?
Which system are you testing?
Thanks.

**Comment by muldjord** [comment]
EDIT: Let me just work on this a bit longer, I have a fix in mind. I'll get back to you.

**Comment by muldjord** [comment]
Ok, I've committed a fix. Please run the following:
```
$ cd
$ cd skytemp/skyscraper
$ git pull
$ make
$ sudo make install
```
Then rerun the command `Skyscraper -p c64 -s thegamesdb -i /home/lubuntu/Escritorio/C64T -f attractmode -e c64`. It shooooould then put the cfg files in `/home/lubuntu/Escritorio/C64T/c64`

Let me know how it goes.

**Comment by qqplayer** [comment]
You are the man! Awesome , is working like a charm :+1: 
Tomorrow I´ll try the full database but with a little test is working perfectly.

**Comment by muldjord** [comment]
Fantastic! Please let me know how it goes. If you don't run into problems, I'll call this feature "done".

**Comment by qqplayer** [comment]
Ok tested and works perfectly , almost 2500 overview.cfg files created for Commodore 64.
Thank so much!!!

PD. Have you ever asked  "segaretro" , to add this website , is the best sega database ever.

**Comment by muldjord** [comment]
Great! I'll mark the feature as "complete". Just had a quick look at sega retro, but they don't appear to have an api, so that's a no-go because of that alone. If you are aware of an api for it, let me know.
