### ISSUE TITLE
Scraper ignores mediaFolder entry in [main]

### ISSUE THREAD

**Issue by Villemann** [muldjord/skyscraper#255]
Scraper ignores mediaFolder entry in [main] (cacheFolder works fine):

I have in config.ini

[main]
mediaFolder="/main/usb0/media"
cacheFolder="/main/usb0/cache"

I dont have any platform specific configs.

and at the begining of the scraping i see:

Platform:           'platform'
Scraping module:    'screenscraper'
Input folder:       '/home/pi/RetroPie/roms/platform'
Game list folder:   '/home/pi/.emulationstation/gamelists/platform'
Covers folder:      '/home/pi/.emulationstation/downloaded_media/platform/covers'
Screenshots folder: '/home/pi/.emulationstation/downloaded_media/platform/screenshots'
Wheels folder:      '/home/pi/.emulationstation/downloaded_media/platform/wheels'
Marquees folder:    '/home/pi/.emulationstation/downloaded_media/platform/marquees'
Videos folder:      '/home/pi/.emulationstation/downloaded_media/platform/videos'
Cache folder:       '/media/usb0/cache'

**Comment by muldjord** [comment]
This is probably due to you running it from the RetroPie script. It uses command-line options to set those folders which overrule the settings from config.ini. It's something that should be changed, but no one has looked into it. So basically it's not a Skyscraper issue, but a RetroPie script issue.

You can solve it by running it from command-line instead. This issue won't be present there. Let me know how it goes.

EDIT: Now that I think about it, you might be able to just set the media download in the RetroPie script to the roms folder, which might remove the command-line parameters which will then let it adhere to the config.ini option instead. Not sure though, but something you can try if you'd rather keep using the RetroPie script to run Skyscraper.

**Comment by Villemann** [comment]
Using command-line i have to set all parameters or everything from config.ini will be also included? 
For example i want to scrape only missing info from specific platform, can i use only -p platform --flags onlymissing or i need to setup all the parameters including all from config.ini?

**Comment by muldjord** [comment]
Everything in config.ini is always used. Setting anything on command-line is added to it, or overrules what is set in config.ini in cases where you have both.

**Comment by Villemann** [comment]
Ok. I think that fixes my problem.
Little sugestion - can you add in menu (via RetroPie script) option for scraping only new/missing game data (--flags onlymissing)?
THX for your great work! :+1:

**Comment by muldjord** [comment]
You're welcome! And good suggestion with `--flags onlymissing` in the script. It will be added very soon (I've already added it to my own fork of RetroPie-Setup, it just needs testing and verification by the maintainer of the official repository).

EDIT: The `--flags onlymissing` has now been added.
