### ISSUE TITLE
Screenscraper not finding items with a query

### ISSUE THREAD

**Issue by CookiePLMonster** [muldjord/skyscraper#258]
It's been a while since I last used Skyscraper, but to the best of my knowledge I'm trying to scrape games correctly, yet with no result:

I am trying to scrap PSX demo discs, in this case - Demo One (Version 1):
https://screenscraper.fr/rominfos.php?romid=200369

A regular Skyscraper query doesn't return results, presumably because I have this game as a `.chd` and this entry is only set for a `.cue`. Therefore, as per the metadata on this entry I tried to override a checksum mismatch by using a `--query` parameter like this:

```
Skyscraper -p psx -s screenscraper --query "md5=53DEA6FA2EBC5A71EC3AA58BC10BB34E" "RetroPie/roms/psx/Demo One (Version 1) (Europe).chd"
```

Despite the fact Screenscraper lists this MD5 for the game, I'm unable to get it to scrape properly. I also tried with `sha1=FCACFD4A3F206AFC495202C7E063E18C500EC25F` and `romnom=DEMO ONE (VERSION 1) (EUROPE).CUE`, without success.

Do note that I don't know if I can rule out an issue with Screenscraper as I don't know if it's possible to send those API requests to Screenscraper manually.

EDIT:
Is this simply the case of Screenscraper only having the title for those entries? Apparently I mentioned this in the past already in https://github.com/muldjord/skyscraper/issues/80#issuecomment-447508321.

**Comment by muldjord** [comment]
Without looking into it (I don't have Skyscraper where I am right now), I am almost positive this is an issue on ScreenScraper's end. Skyscraper sends the query exactly as you type it. So if ScreenScraper returns an entry, it will work. I can't rule out a Skyscraper issue of course, but I don't think it is. If it has to do with the entry only having a title, I'm not sure.

**Comment by R-F-R** [comment]
Sorry to comment on a closed issue, but the checksum search still seems to not work, while I am quite sure  it did last year (some time after this issue was raised).

Maybe I'm doing something wrong, but the output seems to suggest to me that Skyscraper does not use the query (md5 is copied from the screenscraper website):

`Skyscraper -p scummvm -s screenscraper --query "md5=28fca53b2a705ac55d53214baa45fd56" "/home/pi/RetroPie/roms/scummvm/dw2-gb.svm"
`
yields the output
`#1/1 (T1) Pass 1 ---- Game 'dw2-gb' not found :( ----
`

so does a "romnom=..." query 

Edit: 
I was wrong: the "romnom=..." query does actually work.
