### ISSUE TITLE
aliasmap.csv is not used when scraping amiga games 

### ISSUE THREAD

**Issue by wholee** [muldjord/skyscraper#259]
It looks like aliasmap.csv is not used when scraping amiga games.

I have put in multiple games but none of them scraped from screenscraper. 
I tested the substitutions manually and they do return proper results.

my aliasmap.csv:
```
AlienBreedTowerAssault_v1.3_AGA_2331;Alien Breed Tower Assault
DynaBlaster_v1.6_0664;Dynablaster
```
whdload.xml ```<name>``` tag for those games:
```
<name>Alien Breed - Tower Assault [AGA]</name>
<name>Dyna Blaster</name>
```

Manual scrape for "Dyna Blaster" doesn't return any results but "DynaBlaster" does,
"Alien Breed - Tower Assault [AGA]" doesn't return results but "Alien Breed Tower Assault" does.

**Comment by muldjord** [comment]
This is not due to the Amiga platform. ScreenScraper is not search name based, and therefore aliasMap is not used with that module. You need to use, for instance, `thegamesdb` or `mobygames` for it to work.

If you want to force a result from `screenscraper` you can use the `--query` option as documented [here](https://github.com/muldjord/skyscraper/blob/master/docs/CLIHELP.md#--query-string).

**Comment by wholee** [comment]
```
Skyscraper -p amiga -s screenscraper --query "md5=D9291E4D28005B05DCEC569BEB6EAB9F" /home/pi/RetroPie/roms/amiga/DynaBlaster_v1.6_0664.lha
Skyscraper -p amiga -s screenscraper --query "md5=343E1BC21E45EE805C496E7FCDE999C5" /home/pi/RetroPie/roms/amiga/AlienBreedTowerAssault_v1.3_AGA_2331.lha
```
This works.

Thank you.

**Comment by muldjord** [comment]
You're welcome, gonna close this now.
