### ISSUE TITLE
Skyscraper RetroPie setup script and ports

### ISSUE THREAD

**Issue by symbios24** [muldjord/skyscraper#26]
Hello, any change to add skyscraper to the ports section in retropie?

Thanks

**Comment by muldjord** [comment]
I don't know much about the ports myself, but as far as I remember, it's all about adding a script that runs a command in the roms/ports folder. So you can just do that if you want to. I don't see any reason why that won't work. Please let me know if you try it and how it goes. Thank you.

**Comment by symbios24** [comment]
Thanks what i mean is add a script in the retropie-setup script tool that will install skyscraped and put a shortcut to run in ports like for example sshscraperr tool does,i can put a script to run it from ports but im saying the whole thing eg install/run etc

**Comment by muldjord** [comment]
Such a script is not part of the Skyscraper code repository. If anyone makes such a script, it should be added to the RetroPie setup project which I am not involved in. It has been requested quite a lot actually. Simply put, it's not something I would personally be interested in. Read on for an explanation.

The reasoning here being the pressure of support requests it would bring forth by making Skyscraper more accessible to users who don't understand the command line. So my reluctance is based on the fear of that and disgruntled users whom I don't have time to answer properly. Until any software reaches a critical mass of users, it's almost up to the developer to answer everything. I have documented all of it in great detail. But many users simply don't read it, or don't have enough understanding of command lines to even grasp the basics. With that said, I also get many relevant and useful questions and bug reports and I appreciate that immensely!

I am happy so many people like Skyscraper and I am hugely thankful to those who have helped me with suggestions over the course of development so far. It has helped shape Skyscraper into a very powerful tool. But personally, I am determined to let Skyscraper grow slowly and steadily as to not burn myself out. If someone else makes that script and adds it, no problem. That would somehow make sense to me. I just don't feel like making it myself (and I don't have any knowledge on how to do it either).

A bit of long and broad answer I know. But since it has been requested so much, I felt like an explanation was in order. I'll let it sit here for others to see.

**Comment by symbios24** [comment]
i understand no problem,and a last question does your scraper has a gui?

**Comment by symbios24** [comment]
one great addition will be to add support for images with composed visuals

**Comment by symbios24** [comment]
look at this picture in the link at the left is the normal image at the right is the one with composed visuals at the moment only recalbox support this thought screenscraper database

https://www.recalbox.com/blog/images/blog/2017-02-24-scraper/es_scraper.jpg

https://www.recalbox.com/blog/en/post/blog-2017-02-24-scraper/

**Comment by muldjord** [comment]
I am confused. Are you suggesting an artwork compositor? Are you not aware of this: https://github.com/muldjord/skyscraper/blob/master/ARTWORK.md ?

**Comment by symbios24** [comment]
yeah this is the one,no i did not know it supports that,is this scraping images with artwork?

**Comment by muldjord** [comment]
Read the documentation.
