### ISSUE TITLE
Retropie - Symlinks not working

### ISSUE THREAD

**Issue by solskogen** [muldjord/skyscraper#282]
**Describe the bug**
I've got symlinks="true" in the config.ini, but no symlinks are made. 
The videos are downloaded and are in the cache.

**To Reproduce**
Enable videos and symlinks in the ini fille.

**Special circumstances**
RetroPie

**Comment by muldjord** [comment]
Please be more specific. What command are you using and what are you expecting it to do? What section of config.ini are you adding the option to? Please post that so I can verify you didn't add it incorrectly.

The symlinks will be created whenever you generate gamelists with Skyscraper. So if you've set the config correctly and the platform you are generating a gamelist for has videos in the cache, it will symlink those videos to the media output folder instead of copying them. I'm giving you this long explanation since I have no idea if you even know this is how it's supposed to happen due to lack of information in your description.

Please be more aware of this in the future. Thanks. :)

**Comment by solskogen** [comment]
I'm not using it from command line, but from within RetroPis menu. The only
thing I've changed is to use symlinks in config.ini.
What I'm expecting is to not have duplicates of the videos :)

**Comment by muldjord** [comment]
Where did you find documentation for an option called `symlinks="true"`? The correct option is `symlink="true"`. But I need to fix that if it's documented somewhere.

**Comment by solskogen** [comment]
Sorry, my bad. That's just a typo. symlink="true" is what I have in my
config.ini

**Comment by muldjord** [comment]
EDIT: Misread... I'll look into it later.

**Comment by muldjord** [comment]
Did some testing on my own system and `symlink="true"` works fine for me. Tested with:
* Edited config.ini and added symlink="true" to the [main] section
* Edited config.ini and added videos="true" to the [main] section

Then ran:
```
$ Skyscraper -p videopac -s screenscraper --refresh
$ Skyscraper -p videopac
```
This gave me a bunch of these in `/home/pi/RetroPie/roms/videopac/media/videos` which is what my media output folder is set to:
```
lrwxrwxrwx 1 pi pi  107 Jan 25 09:13 'Air Battle (Europe).mp4' -> /home/pi/.skyscraper/cache/videopac/videos/screenscraper/2ff1fad8eb74399e5575d1d9e6e42a786008e8b4.mp4
```
As you can see this is a symbolic link to the video file directly inside the Skyscraper cache, as expected. This is how yours should look too when you fix your config issue, whatever it might be.

**Comment by solskogen** [comment]
Closing this :)
