### ISSUE TITLE
Logo Suggestion

### ISSUE THREAD

**Issue by SecularSteve** [muldjord/skyscraper#289]
**Describe the feature / request**
What it says in the title.
I made a logo, and I'm only suggesting an implementation by your own volition (Made in Inkscape, CC BY-SA 4.0).

**Additional context**
I don't consider myself an "artisté", but It's a rough estimate of my vision.

![SkySkraper](https://user-images.githubusercontent.com/33793273/108566424-b2b2ea80-7306-11eb-9f9c-cd675ede0063.png)

ZIP contains PNG and SVG...

[SkySkraper.zip](https://github.com/muldjord/skyscraper/files/6013168/SkySkraper.zip)

**Comment by muldjord** [comment]
If I ever create a UI that needs a logo this is very much in line with what I have in my mind. The skyscrapers being game media is a nice touch. But I will probably make it myself, since I also work as a graphics artist on several projects and it is something I very much enjoy doing.
And although this is along the lines of what I am looking for, it's not quite it. I want "Skyscraper" spelled out entirely. And I want the bottom of the letters to be halfway covered by the skyscrapers all the way along the bottom. That's what I've been playing around with in my head anyway.

But it is really cool to see stuff like this from the users. So thank you for inspiring me.
