### ISSUE TITLE
Custom platform -p for custom systems

### ISSUE THREAD

**Issue by mixpc** [muldjord/skyscraper#291]
Hi,

I have created two custom systems:
MAME 2003 Lite
MAME 2010

arcade and mame-libretro folders are already busy so I have had to create these two specific systems to host those two specific romsets.

```
es_systems.cfg
  <system>
    <name>mame2003-lite-retropie</name>
    <fullname>MAME 2003 Lite</fullname>
    <path>/home/user/RetroPie/roms/mame2003-lite-retropie</path>
    <extension>.7z .cue .fba .iso .zip .7Z .CUE .FBA .ISO .ZIP</extension>
    <command>/opt/retropie/supplementary/runcommand/runcommand.sh 0 _SYS_ arcade %ROM%</command>
    <platform>mame2003-lite-retropie</platform>
    <theme>mame2003-lite-retropie</theme>
  </system>
  <system>
    <name>mame2010-retropie</name>
    <fullname>MAME 2010</fullname>
    <path>/home/user/RetroPie/roms/mame2010-retropie</path>
    <extension>.7z .cue .fba .iso .zip .7Z .CUE .FBA .ISO .ZIP</extension>
    <command>/opt/retropie/supplementary/runcommand/runcommand.sh 0 _SYS_ arcade %ROM%</command>
    <platform>mame2010-retropie</platform>
    <theme>mame2010-retropie</theme>
  </system>
```

Could skyscraper allow custom platform -p mame2003-lite-retropie that writes screenshot data to
`/home/user/RetroPie/roms/mame2003-lite-retropie`
?

**Comment by muldjord** [comment]
Yes, this is already on the road-map as seen [here](https://github.com/muldjord/skyscraper/blob/master/README.md#version-xxx-features-under-consideration-all-unimplemented) (bulletpoint no. 5). But I am not currently expanding functionality of Skyscraper due to pursuing other projects, so don't hold your breath for it to happen anytime soon. :)

Closing.
