### ISSUE TITLE
Sega CD

### ISSUE THREAD

**Issue by trevor7oaks** [muldjord/skyscraper#30]
Hi, the scraper can’t find media for segacd, screenscraper is usually reliable but can’t find any roms, could this be because the system is also referred to as megacd?

**Comment by muldjord** [comment]
Please take more time describing this issue, this is nowhere near enough info for me to work with. Just saying "roms", what does that mean? What file type? Where are your files located? What command are you using to scrape them?

**Comment by trevor7oaks** [comment]
Sorry. They are chd format files, in the segacd folder on a HDD. Gamesdb finds all data but no media, screenscraper database returns the ‘can’t find’ error for each. I have previously installed your scraper and and run via the terminal on my Pi using the command Skyscraper

**Comment by muldjord** [comment]
Yes, thegamesdb's media servers are down and have been for a while, so it won't find any media using that module. Concerning screenscraper, there's two possible reasons. Either the .chd's simply aren't in their database. Or the platform is using an alias I am not aware of. I will check if it has the "mega cd" alias on screenscraper and add it if necessary. I'll be back later with an update to this issue.

**Comment by muldjord** [comment]
I have now added the necessary 'mega-cd' alias to the segacd platform. As you mentioned this alias is used by screenscraper. Please update the scraper as described [here](https://github.com/muldjord/skyscraper#updating-skyscraper) and test it. If your .chd files aren't found after the update, it is most likely because screenscraper doesn't have the files in their database.

**Comment by trevor7oaks** [comment]
Hi, still won’t find any art so I guess it’s that the chd format isn’t recognised. If I download the art and add them to the correct folders will your scraper pick them up when I run a scrape from the local dB?

**Comment by jt3writer** [comment]
I am also having an issue with getting Sega CD info/art from screenscraper. I checked the site and it appears my filenames are known filenames, yet when I run Skyscraper, I get the "not found" error. For example, "Sewer Shark (U).cue" is the name of one of my files, and this is one of the names listed on screenscraper's Sewer Shark "ROM/ISOs" filenames list. All the art/text is there, it's just not being found for some reason. For -p, I've tried both segacd and mega-cd. Any other suggestions? Thank you!

**Comment by chipsnblip** [comment]
could it be an issue with name tables: "Nom du jeu (interne ScreenScraper)" vs "Nom du jeu (par Région)"?

 i don't know enough about programming to investigate and provide a patch, but i did some testing with 
 what few segacd roms i have (7 in total), and think it might have something to do with games without a region name.  i registered an account at screenscraper and proposed a USA region name for [Batman Returns](https://www.screenscraper.fr/gameinfos.php?plateforme=20&gameid=12716), but my proposal is either being reviewed and their database just hasn't refreshed yet, or was rejected outright.  

upon further testing, i scraped an empty file named "Shadow of the Beast II (1994)(Psygnosis)(US).7z" [Beast II](https://www.screenscraper.fr/gameinfos.php?plateforme=20&gameid=12752) which has a region name, and it was successfully scraped.

perhaps we will need to contribute to the database, or Skyscraper could use the internal name as a fallback in certain cases?

i hope this was somewhat helpful, if not i'm sorry for the noise =)

**Comment by muldjord** [comment]
Hi guys, thank you for the detailed information, I will look into this when I get the time. :)

**Comment by jt3writer** [comment]
Yes, thanks chipsnblip for also trying some things out. The region suggestion is a good one, but I will note that some of my "not found" files do include (US). This also happens for a handful of PSX files, which also have the region tag. I definitely don't know enough about all this to offer much more, but one thing I noticed is that when I do an MD5 check on some files, screenscraper may have everything in uppercase, while the file on my computer shows lowercase. Don't know if that would make a difference. Anyway, I went ahead and downloaded all the images and imported everything manually.

**Comment by chipsnblip** [comment]
quick update, i just tried scraping segacd again, and this time it picked up Batman Returns (the one i added a region name for)!  i think it just took a while for screenscraper's database to refresh.

here's the terminal output if you need it: https://gist.github.com/chipsnblip/65c24c74cfb0f8a06a9d97465c891570

i'm going to add a couple more US region names (Mary Shelly's Frankenstein, and Terminator, The) and will try scraping again in a few days time to confirm.

**Comment by chipsnblip** [comment]
@jt3writer   do you happen to recall any titles that had a 'Game Name (by Region)' yet still didn't scrape?  maybe they're in your skipped log by chance (~/.skyscraper/skipped-screenscraper.txt)?

with regard to my recent submissions, the region names for [Mary Shelley's Frankenstein](https://www.screenscraper.fr/gameinfos.php?plateforme=20&gameid=97354) and [The Terminator](https://www.screenscraper.fr/gameinfos.php?plateforme=20&gameid=12709) were finally accepted, and it appears the moderator team even propagated them over to the 'Name of the game (Internal ScreenScraper)' on my behalf.  i think before, there was an internal name but no one was yet credited for its proposal (blank).  possibly due to it being an automated initial database import, and they would like to eventually replace those entries with a verified, human proposal?

at any rate, those two games are scraped now.  so there is a lengthy delay between adding metadata and being able to scrape it, at least 24 hours apparently.

i added the USA region titles to all my other segacd roms, so if all goes well it's just a matter of time before i can scrape them.  i will try to work on adding the rest of the US titles, but no guarantees (i must admit the screenscraper website is very sluggish and not so user-friendly)

edit: just a quick update, all the roms i added names for are now scraped.

**Comment by chipsnblip** [comment]
i've been slowly chipping away at adding segacd USA region titles to the screenscraper.fr database and currently on letter E, so if anyone wants to start from Z and meet me in the middle that would be awesome (if not, that's fine).  i've been using a combination of segaretro.org and mobygames.com as reference sources.

so hopefully those will get accepted and scraping this system will be that much less of a hassle for my fellow retro-gamers :)  i don't think i'll be motivated enough to add other region titles at this time, unfortunately.

**edit**: finished adding region titles for all games that had a US release. give it a few days time before rescraping segacd.

**Comment by muldjord** [comment]
EDIT: A bit more info on how the screenscraper module works as of 2.5.3 (please update if you don't have it). The first pass Skyscraper tries searching with both filename, sha1 and md5 sum. If a result is returned with this, it is clearly a winner! :D For pass 2-4 it first tries with sha1 only, then md5 only and lastly filename only. When searching by filename, it has to be a 100% fit. And if it's found, it doesn't matter if the file is empty, it will still be found as that game - just tested that, and it works.

POST BEFORE EDIT:
Hi guys, I've been looking into this a bit, and it works just fine here on my end. If I create a file called "Sewer Shark (U).cue" it scrapes fine with screenscraper.

This is my command:
```
Skyscraper -p segacd -s screenscraper --updatedb --region us
```
Skyscraper uses a priority based search when it comes to the regions. Even if you set '--region us' it will always try other regions afterwards if none is found. So I don't think whatever issues you are seeing has to do missing us region names.

Skyscraper doesn't use the bracket information for anything such as (US) or similar. So that is not the case either.

**Comment by jt3writer** [comment]
It appears I was using the same command. I will give the update a try and see if that makes a difference. Thanks for looking into this and the explanations!

**Comment by muldjord** [comment]
Hey guys, I might have fixed some of the issues you are seeing with segacd and megacd in the newest 2.5.5 release. Please update and check if it finds more roms with the 'screenscraper' module. The fix is related to an 'ss' region Screenscraper uses internally, which I didn't recognize in 2.5.4.

**Comment by trevor7oaks** [comment]
Thank you. I will try later and let you know

**Comment by jt3writer** [comment]
I just tried it and it found every one. Looks like this trick worked. Thanks!

**Comment by muldjord** [comment]
Phew, I'm glad to hear that. You're welcome! :)
