### ISSUE TITLE
"Unknown option: unattend" error

### ISSUE THREAD

**Issue by bbilford83** [muldjord/skyscraper#312]
Hi there.  Per my title, I haven't been able to vacuum any platforms since I updated skyscraper relatively recently.  It acts like it's "thinking" for a bit but then I get "Unknown option: unattend" and it pops me back to the main skyscraper menu.  Would appreciate any advice if it's not a system-wide issue - thanks either way.

**Comment by muldjord** [comment]
This is not related to the vacuuming. As Skyscraper tells you, you are using an unknown option. The `--unattend` option has been deprecated for a year and was recently removed from Skyscraper after a grace period (of a year). It has been moved into the `--flags unattend` option together with many other options. Please check `--help` for more info. Just use `--flags unattend` instead of `--unattend`.

**Comment by muldjord** [comment]
I've corrected the title as it was misleading to avoid confusing other users. Just to be clear if others read this, vacuuming works fine and was never broken. This is entirely due to the use of the deprecated  `--unattend` option. Many other options have been moved into the `--flags` option.

Always remember to check the documentation [here](https://github.com/muldjord/skyscraper/blob/master/docs/CLIHELP.md).

**Comment by bbilford83** [comment]
Thank you very much for the quick response, and sorry for causing confusion.  I've read through the documentation but I'm still confused as I'm not running anything through the command line - just through the retropie_setup.sh menu. I'm not really familiar with linux but I gather maybe from your documentation that I might be able to fix this through the config.ini?  I don't know how I would've changed anything in the first place...

**Comment by muldjord** [comment]
You are probably running an old version of the RetroPie script. It has been fixed about a month ago. Please update the script through the menus and try again. In general I suggest updating it regularly to avoid issues like this.

**Comment by bbilford83** [comment]
That was it!  Thank you so much for the advice, and sorry again for misleading with my original post.
