### ISSUE TITLE
[Help] How to add a colon symbol in Pegasus metadata.txt for launch command

### ISSUE THREAD

**Issue by SoumyBhow** [muldjord/skyscraper#315]
Hello. I'm currently trying out Skyscraper for my Android device and I'm generating assets for PPSSPP. Here is the launch command for Pegasus which I've put in the config.ini:
launch="am start --user 0  
-a android.intent.action.VIEW 
-n org.ppsspp.ppsspp/.PpssppActivity 
-d "file://{file.path}""

That last line uses a colon, yet it doesn't show up in the metadata.txt. Instead, that line is just:
 -d "file//{file.path}"

How can I specify the colon in the config.ini?

**Comment by muldjord** [comment]
Short answer is "You can't". I just had a look at the code, and I do a search replace to remove all colons. The problem is, I can't remember why, but I know I do it for a reason. I think it's related to my Pegasus game list parser, that does a lot of checks for colons to determine the values, but I'm not sure.

So allowing it will surely break something unless I spend some time to figure out why I do it, and work around it. I probably will at some point, but I won't promise when that'll be as I would have to sit down and re-learn how Pegasus game lists work. I haven't touched that code for a long time.

**Comment by SoumyBhow** [comment]
Understood. Guess I'll have to manually add the colons in. Thank you nonetheless! Closing this issue.
