### ISSUE TITLE
Nintendo Switch platform

### ISSUE THREAD

**Issue by Kadagaden** [muldjord/skyscraper#318]
Can you add Nintendo Switch to platforms? I'm using pegasus frontend on my Linux machine and there is no option for Switch.

**Comment by muldjord** [comment]
I need the information as provided in this example: https://retropie.org.uk/docs/Thomson-MOTO/

Most importantly:
* What emulator would be using it?
* Does the emulator require a special file structure to launch games or is it simple flat zip files (which would make my job very easy, otherwise I probably won't support it right now)?
* What file formats does it support?

Thanks.

**Comment by Redemp** [comment]
> I need the information as provided in this example: https://retropie.org.uk/docs/Thomson-MOTO/
> 
> Most importantly:
> 
>     * What emulator would be using it?
> 
>     * Does the emulator require a special file structure to launch games or is it simple flat zip files (which would make my job very easy, otherwise I probably won't support it right now)?
> 
>     * What file formats does it support?
> 
> 
> Thanks.

 * What emulator would be using it?
 * Answer: yuzu & Ryujinx
 
 * Does the emulator require a special file structure to launch games or is it simple flat zip files (which would make my job very    easy, otherwise I probably won't support it right now)?
 
 * Answer:  .xci & .nsp
 
 :fingers_crossed:

**Comment by muldjord** [comment]
`switch` platform added and Skyscraper 3.7.3 released. I can't test it myself, so let me know if you run into trouble.
