### ISSUE TITLE
Broken import for XML textuals

### ISSUE THREAD

**Issue by swmarc** [muldjord/skyscraper#327]
**Describe the bug**
When trying to import an XML based textual with a XML based definitions.dat, no resource is imported.

The attached patch file demonstrates how I solved it, but I don't know if it would be your intended solution.
It fixes parsing of textuals with closing tags like defined in XML.
Without trimming, `QByteArray::indexOf()` does not find the string representation of the closing tag due to escape characters and returns `-1`.

From reviewing the code it looks like that simple structured textuals (like from Skyscraper's documentation) are not affected, but I did not test this.

**To Reproduce**
Sample files attached to this report.
Please note that the file extension `.txt` was added by me to be able to attach them to this report since allowed extensions on GitHub are limited.

1. Create a XML based textual in `import/<platform>/textual/<exact-file-name>.xml`.
2. Create the desired `definitions.dat` in `import/<platform>`.
3. Run Skyscraper with eg. `skyscraper -p <platform> -s import`.

**Terminal output**
Terminal outputs that no textual resource was imported.

**Technical information**
 - Skyscraper version: 3.7.0
 - OS: Ubuntu
 - OS Version: 21.10
[0001-Trim-escape-characters-from-closing-tags.txt](https://github.com/muldjord/skyscraper/files/7891586/0001-Trim-escape-characters-from-closing-tags.txt)
[definitions.dat.txt](https://github.com/muldjord/skyscraper/files/7891590/definitions.dat.txt)
[1st Division Manager (Europe).xml.txt](https://github.com/muldjord/skyscraper/files/7891591/1st.Division.Manager.Europe.xml.txt)

**Comment by muldjord** [comment]
Yeah, this is due to your newlines differing from the definitions to the xml file. In your definitions file you have newline+carriage-return (the old-school Windows way of doing things). In your xml file you only have a newline. Trimming the lines is not a solution, as it breaks it for people who have definitions where the right-most pattern is simply the newline. Trimming removes those and causes those use-cases to fail.

You should simply use an editor that uses newlines-only and correct your definiteions.dat file. Then it'll work. Try opening it in a hex editor and compare the two files. You will find that the definitions.dat file has two bytes at the end of each line instead of one.

**Comment by swmarc** [comment]
Yes, you're right. It's just rather unexpected.
But since it's not a compliant XML parser & the docs state an exact match between textuals and the definitions.dat I guess it's fine as is.
I apologize the hassle. Thanks for your time.

**Comment by muldjord** [comment]
I agree, it is a bit hacky, but it makes sure it works for pretty much any format users throw at it as long as they understand that types of whitespaces are important.

Closing.
