### ISSUE TITLE
File format .chd 

### ISSUE THREAD

**Issue by marioacjr** [muldjord/skyscraper#346]
**Describe the bug**
Hi. When trying to scrape the ps2 system, no files inside the folder were processed. All the files are in .chd format. When renaming one of the games from .chd to .iso, the scrape worked fine. I tried using --flags forcefilename, but was not successful. I tried changing the line forceFilename="false" in the config.ini file, but that didn't work either.

I believe that the .chd extension can be added for the ps2 system in src/platform.cpp line 495.
The forcefilename flag does not seem to have worked for me.

**Terminal output**
![image](https://user-images.githubusercontent.com/18449490/174825746-3256a087-c2a0-4a48-93a7-1339c8be87ac.png)

**Technical information**
 - Skyscraper version: 3.7.6
 - OS: Ubuntu 20.04.4 LTS (Focal Fossa) 64-bit
 - OS Version: Linux kernel 5.13.0-51-generic x86_64

**Comment by adelpha** [comment]
@marioacjr You're right about ps2 not supporting .chd by default (which it should, since PCSX2 now supports CHD), but the way to fix this yourself is to just add:

 `--addext "*.chd"`

to your Skyscraper launch command. In your example above that would be:

`./Skyscraper -p ps2 -s Screenscraper  --addext "*.chd"`

**Comment by marioacjr** [comment]
Thanks! It worked. Sorry to post a question here for this.
