### ISSUE TITLE
Support .m3u files for multi-disc PSX titles

### ISSUE THREAD

**Issue by jpunzel** [muldjord/skyscraper#38]
All of my PSX games are in .bin/.cue format. In order to allow for easy disc swapping with RetroPie's pcsx emulator, I wrote a script to go through my collection and create .m3u "playlists" listing each game's renamed .cue files, as described here: 
https://github.com/RetroPie/RetroPie-Setup/wiki/Playstation-1#m3u-playlist-for-multi-disc-games

My setup is exactly the same as outlined in the above documentation. For example, I have the following files in my roms directory:
```
-rw-rw-r-- 1 pi pi 718738272 Dec 25  1996 Xenogears (USA) (Disc 1).bin
-rw-rw-r-- 1 pi pi        90 Dec 25  1996 Xenogears (USA) (Disc 1).CD1
-rw-rw-r-- 1 pi pi 688700880 Dec 25  1996 Xenogears (USA) (Disc 2).bin
-rw-rw-r-- 1 pi pi        90 Dec 25  1996 Xenogears (USA) (Disc 2).CD2
-rw-rw-r-- 1 pi pi        58 Jul 28 18:46 Xenogears (USA).m3u
```
where the `.CD1` and `.CD2` files are simply renamed .cue files for those discs, and `Xenogears (USA).m3u` is a plaintext file with the following contents:
```
Xenogears (USA) (Disc 1).CD1
Xenogears (USA) (Disc 2).CD2
```

However, it doesn't appear that this game is successfully scraped. I do get an entry in my gamelist.xml for this game but all the fields appear to be empty. Most multi-disc/m3u games don't appear at all in the gamelist.xml (I'm not yet sure what explains this discrepancy, although I do have plenty of cached data in localdb).

There are references to m3u in the formats list in `src/platform.cpp`, so I hope this is an intended feature and that it wouldn't be too hard to implement.

**Comment by muldjord** [comment]
This is related to missing .m3u files with the 'screenscraper' module I believe. Please try this: "Skyscraper -p psx -s thegamesdb --updatedb" and let me know if that works.

**Comment by jpunzel** [comment]
You're right, it does work with the `thegamesdb` module! But would it be possible to get it working with screenscraper? The 1000 request limit with `thegamesdb` means that I can't even scrape my entire library (I have a complete collection). In fact, I had to hack in QNetworkProxy support to your `NetComm` class to test it out from a different IP address - I'll put in a separate feature request about that :)

**Comment by muldjord** [comment]
.m3u files will work with screenscraper if they are added to the screenscraper db. That is the only way to get it working with their db. :)

**Comment by BlackDog6469** [comment]
Apologies to necro this thread, but it's the first result in google for m3u creation for multi-disk titles (which is applicable also to other emulators). As the original author did not post his script for generating the m3u files in the first place, I have included some code below to help other users stumbling on this topic, in the form of a bash script which will generate m3u files for multi disk images - 

Note: This is designed to run in a single parent directory and will not work with subfolders.

Replace (*.st|*.stx) to use the script with file formats of your choosing (I made the script for atari ST games as I had thousands of them but it will also work for PSX with the correct extensions added).

```
#!/bin/bash

shopt -s extglob globstar nullglob
for filename in **/*(*.st|*.stx)
do
if [[ $filename == *"Disk"* ]]; then
croppedfilename=${filename//\(Disk*\)/}
echo "$filename" >> "$croppedfilename.m3u"
fi
done
```

Note that in order for the script to work, the files must be named consistently.

Finally, feel free to change the text "Disk" with "Disc" depending on the names in your ROM files. Or feel free to adjust the script so that it will work for both!

Just thought this might help someone further down the line.
