### ISSUE TITLE
MameDB - Potential new source

### ISSUE THREAD

**Issue by fOmey** [muldjord/skyscraper#5]
ArcadeDB seems to be down for maintenance, not expected to be up till early next year as per their forum. So currently scraping arcade rom's is out of the question.

I came across the following websites which seem to both have a pretty good databases: mamedb.org & mamedb.blu-ferret.co.uk

I like the way mamedb.blue-ferret.co.uk search is formatted, the URL's point directly to the rom information page.. mamedb.org seems to use unique ID's for each of roms info pages, so they would need to be grabbed from the search results list.. bit more coding I guess.

The mamedb.blu-ferrest.co.uk website seems a little buggy when navigating using my web browser, for whatever reason my browser was downloading the href PHP page links... guess apache isn't configured correctly or something. Although when punching the searches directly into the URL it works really well !

Anyway... mamedb.blue-ferret search pattern is as follows: http://mamedb.blu-ferret.co.uk/game/frogger

They don't feature any video's, however they both seem to include titles, screenshots & marquees.

**Comment by muldjord** [comment]
I am well aware of blu-ferret's mirror and implementation. It was supported by Skyscraper in the early days, but I had to remove A LOT of the sources since they either didn't reply to my emails or don't condone scraping. Which is absolutely understandable. Both the sources you list have been supported, but isn't anymore (and won't be again), sorry.
