### ISSUE TITLE
Zip archives produce no matches in localdb

### ISSUE THREAD

**Issue by inverimus** [muldjord/skyscraper#50]
**Describe the bug**
Zip archives do not match anything in localdb.

**To Reproduce**
Tried zipping my roms and then scraping from localdb and it finds nothing when I had 100% when they were just rom files.

**Special circumstances**
None

**Terminal output**
No matches.

**Technical information**
 - Skyscraper version: 2.7.1
 - Internet connection: cable
 - OS: RetroPIe
 - OS Version: 4.4

**Additional context**
Originally I tried 7z archives and then zip archives but neither worked. I saw there were old notes about zip archives being supported, but I am not sure how they are supported since screenscraper always fails to find anything for archived roms.

**Comment by muldjord** [comment]
This is not a bug, it is expected behaviour. If you zip your roms you effectively change the fingerprint and the suffix of your rom files, which means they are no longer the same files and therefore won't match with the entries in the cache. You will have to start over and scrape your newly zipped files, unzip your files again or manually change the sha1 checksums in the cache.

There are many ways to zip a file, and zipping them manually will almost always give you issues as the sources will have trouble recognizing them. So rule of thumb: Don't zip your rom files unless they where zipped when you got them.

I hope this clears things up a bit.

**Comment by muldjord** [comment]
Currently implementing an '--unpack' option for Skyscraper 2.7.4 that enables what you are looking for. Keep an eye out for the release soon. Note though that the id in the localdb is still based on the checksum of the zip or 7z file, so this is merely to make it easier for the 'screenscraper' module to identify roms you have zipped yourself.

**Comment by muldjord** [comment]
2.7.4 out with --unpack option.
