### ISSUE TITLE
Not matching screenscraper by filename

### ISSUE THREAD

**Issue by Vynce** [muldjord/skyscraper#57]
Skyscraper found matches for everything with the screenscraper module except three NES roms (likely because I "fixed" their headers). The filenames of the three roms that aren't matching are:
```
R.B.I. Baseball (USA).zip
Super Mario Bros. 2 (USA) (Rev A).zip
Super Mario Bros. 3 (USA) (Rev A).zip
```

Skyscraper v2.7.4 on Retropie 4.4
```
$ Skyscraper -p nes -s screenscraper --pretend --unpack --verbosity 3 '/home/pi/RetroPie/roms/nes/Super Mario Bros. 2 (USA) (Rev A).zip'

#1/1 (T1) Pass 1 Pass 2 Pass 3 Pass 4 ---- Game 'Super Mario Bros. 2 (USA) (Rev A)' not found :( ----
Debug output:
Tried with combined filename, md5, sha1: 'Super%20Mario%20Bros.%202%20%28USA%29%20%28Rev%20A%29.zip', '5544A3A89672982BCC4E79946458423A4FF40548', '8D23BB4F6B0234C49E030F9CB5D15373'
Platform: nes
Tried with sha1 only: 5544A3A89672982BCC4E79946458423A4FF40548
Platform: nes
Tried with md5 only: 8D23BB4F6B0234C49E030F9CB5D15373
Platform: nes
Tried with filename only: Super%20Mario%20Bros.%202%20%28USA%29%20%28Rev%20A%29.zip
Platform: nes
```

The sha1/md5 hashes don't match anything on screenscraper.fr, but both the .zip filename and the compressed .nes filename [exactly match several entries in their database](https://screenscraper.fr/gameinfos.php?gameid=1248&action=onglet&zone=gameinfosroms).

It seems like these should still find matches based on filename (?). Let me know if I can help test/debug.

**Comment by muldjord** [comment]
Hm, the response I get from ScreenScraper is simply "Rom/File not found". I'll dig a little deeper to see if I can figure this out. Thanks for reporting it.

**Comment by muldjord** [comment]
Ok, so I think I've gotten to the bottom of this. When asking ScreenScraper for a game, it needs to return just a single entry for it to form a reply instead of an error. Skyscraper works by first trying with both the checksums and the filename combined. This will always only ever match with a single rom and, therefore, game. But, if this fails and the file doesn't match with the checksums, it will try first with only the checksums, and lastly only with the filename. For each of these requests there's one rule that applies on ScreenScrapers side of things: If more than one entry matches, return an error. And since your file doesn't match with any of the checksums, those requests fail. So lastly it tries with only the filename. But because the filenames exists several times in their database, it can't return a unique entry, and it therefore returns an error.

And that's what is happening here. In other words: This is a ScreenScraper related issue, and not a Skyscraper related issue. For it to work, your files needs to match with at least one of the checksums of the ScreenScraper files, or the filename needs to be unique in their database.

If you have more input on this, please let me know. Otherwise I'll close it.

**Comment by Vynce** [comment]
Ah, that's too bad. Thanks for the detailed explanation.

Any chance you could add support for searching by `gameid` or perhaps a manually-specified hash? I think the problem there would be how to communicate that info to Skyscraper. Here are some ideas. All of these could use a custom hash (just copy a relevant one from the ss website) in place of a gameid if that's easier than adding gameid support.

- Add the option to fall back to an interactive mode if a match can't be found using the current methods. So Skyscraper would try filename + hashes, etc, and finally prompt for a gameid that you can type in.
- Add a rom name to gameid mapping to the [platform] or [screenscraper] section of the config.ini. I'm not sure if your ini format supports arbitrary strings as keys though.
    ```
    [nes]
    Super Mario Bros. 2 (USA) (Rev A)=1248
    ```
- Have a text file next to the rom that specifies the gameid.
    ```
    $ cat '~/RetroPie/roms/nes/Super Mario Bros. 2 (USA) (Rev A).id'
    1248
    ```
- Add a new `--gameid` command line argument that's only relevant when you specify a single rom.
    ```
    $ Skyscraper -p nes -s screenscraper --pretend --unpack --gameid 1248 
    '~/RetroPie/roms/nes/Super Mario Bros. 2 (USA) (Rev A).zip'
    ```

I realize that this would be a very niche feature, so no worries if you don't think it's worth the effort, but it would be cool if there was *some* way to manually correct/specify a match :smile:.

**Comment by muldjord** [comment]
I've had one other request for this, so it's in the pipeline for consideration. :) And I agree, it would give the user better control. It would only be relevant for ScreenScraper though so that's my only gripe with it. But it's new information to me that it won't return data if there's duplicate filenames in their db, so it makes more sense to me now. Before I knew that it was way easier to just rename the file and that would fix it.

**Comment by muldjord** [comment]
I've been pondering this some more, and I've come up with a way that makes this usable for all of the scraping modules. It would simply let you define the request pair yourself. For instance, for screenscraper it needs either the sha1, md5 or romnom (rom name in French) attributes in the GET call. So I could allow you to overwrite that call with whatever you please. So for screenscraper, you would need to put in, for instance, '--searchname sha1=[sha1 checksum] and it would use that as a 1-pass for the request for a single file.

This would actually also tidy up my code a bit, as I am doing this using different methods for each module. Implementing this overall, I would end up with just one function doing this, which I like. So that is basically what made me want to look into this. You could say that consolidating those functions into one, is what enables this option in the first place. But that consolidation in itself makes sense, and the fact that it allows your request to be met, is just a bonus. :)

I'll let this boil in my mind for a few days and look into it. I need to make sure I don't break anything.

**Comment by Vynce** [comment]
Cool, that would work for me!

**Comment by muldjord** [comment]
I'm actually almost done coding this. The search code is much cleaner now! It's pretty cool. I'll work through the remaining code and do testing over the coming days. I'll let you know when 2.7.5 is released with this feature. :)

**Comment by muldjord** [comment]
If you want to help testing it, it's on the master branch now. But you'd need to clone the git repository of course, instead of using the normal install procedure. A complete install is as follows:
```
$ cd
$ git clone https://github.com/muldjord/skyscraper.git
$ cd skyscraper
$ qmake
$ make
$ sudo make install
```
That will compile and install the in-development version. The feature is used as follows:
```
Skyscraper -p [platform] -s screenscraper --refresh --query md5=[custom checksum] /[path]/[to]/[filename.zip]
```
The filename at the end is just a single filename as usual. Using the above command will search the rom using the md5 sum provided. You can also use 'romnom=[filename]', 'sha1=[checksum]' or a combination of them with '&' between them. For the filename based modules it's simply '--query search+name' where +'s equals spaces (this is a url thing).

Please let me know if you do test it out.

**Comment by Vynce** [comment]
As a side note, here's a dirty hack for anyone else that wants to update to the tip of master using the existing `update_skyscraper.sh` script instead of cloning the repo. It's pretty cool that the update script makes this so easy 😄.
1. `$ cd ~/skysource`
2. Use nano or vi to edit `update_skyscraper.sh`
3. Change the `LATEST` line at the top to `LATEST='master'`. This will use an archive of the master branch instead of the latest release.
4. `$ ./update_skyscraper.sh`
5. The source package that gets downloaded will replace `update_skyscraper.sh`, so updating again in the future will download the latest versioned release. This is handy if you just want to update to the tip of master once and then go back to versioned releases for subsequent updates.

@muldjord, if you regularly need to ask people to test changes on master, you could consider making this a command line argument. So something like `./update_skyscraper.sh unreleased` would download the `master.tar.gz` archive.

**Comment by muldjord** [comment]
Glad it works, I'll do more testing for the other modules to make sure they still work as expected before releasing it.

Concerning de-mystifying how to compile from master, I prefer just telling people how to do so when I need it (but thanks for the suggestions). It happens that I break master for a while when doing larger refactorings and I do not wish to support that branch for the users. You could argue that I should be working on subbranches instead, but I just don't want the hassle of it on this project. :)
