### ISSUE TITLE
Specific game name scrape

### ISSUE THREAD

**Issue by HoraceAndTheSpider** [muldjord/skyscraper#6]
Hi there

I know the scraper has tried to get away from using name matching and has the “match percentage “ option.... 

But since .uae files can’t be matched by A checksum, is there any way to scrape a single game, on a full name match basis only? Or even to provide it a specific page to grab the info from?

 I have some Amiga games that don’t return a result but are clearly on openretro and when doing game boy games I was very surprised to see Pokemon Red didn’t achieve a match!

I am going to try and build up a good local database, although I don’t always feel it is asking me questions about adding to existing files when it should... :/

**Comment by muldjord** [comment]
Concerning lack of matches from Openretro that exists, can you verify if those are "unpublished" or otherwise marked down in Openretro? I currently don't include "unpublished" and some of the others as far as I recall.
On a more general note concerning this, I am strongly considering completely rewriting the comparison functions to be aware of a bunch of stuff I currently have halfway hardcoded. Stuff like game sequels and subtitles. Currently it works, but also brings in a bunch of false positives. This can be done better and is probably the single most important aspect of scraping. :) So this is of high priority together with an improved userinput based mode.

It is not currently possible to supply a name on command line that it will search for. You can sortof do that by creating an empty folder, touch the filename you wish to scrape in there, so the folder holds just that one file. Then choose the folder for input folder with '-i [folder]' and also set the platform of course. Then it will scrape just that one file, provide a gamelist.xml in the folder, and also save the artwork. You can then handweave it into the actual gamelist.xml.

**Comment by HoraceAndTheSpider** [comment]
Ok... a lot to take in there!

Have you considered some kind of localdb “manager” so we can manually add files (or scrape links etc) in for specific games? Might be cause of less headache than the “hand weave”!

**Comment by muldjord** [comment]
I have plans for many things! :D And little time to implement them. One of my plans concerns better localdb tools, which will allow you to manage it better. But it will mostly be used for cleaning up old data.

As for adding games to it, I suggest using the import function which relatively easily allows you to enter game data into the localdb using basically any format you like.
