### ISSUE TITLE
Precompiled binaries for different platforms

### ISSUE THREAD

**Issue by paradadf** [muldjord/skyscraper#7]
Hi! First of all, many thanks for your work!

I wanted to suggest you to either share pre-compiled binaries or set up an automatic build system so that potential users grow bigger and can enjoy your work. Users on Retropie or a full Linux distro don‘t have it very difficult, but Recalbox and Windows users would need to learn to too much stuff to even dare to try.

Best regards!

**Comment by muldjord** [comment]
It's been requested before. I would love to do that. The limiting factor here being time, machine power and a missing Windows license. I'd have to built VM's or physical machines for each built environment. I'd also have to set up a Jenkins server or similar and I'd have to test each release. So basically it's a huge amount of work, for something I don't really have the time or interest in doing (interest as in: I'm a coder, not a built environment specialist, so my knowledge is limited).

If someone wants to step in and help out, let me know.

**Comment by davestephens** [comment]
I'm a DevOps Engineer by trade, would love to help you get this working as a thanks for writing a tool that ACTUALLY WORKS without a daft gui ;-). I'll fork and see what I can conjure up...

**Comment by muldjord** [comment]
Awesome, thanks! I am unsure exactly what the potential gain is from this after Skyscraper was added officially to RetroPie to be honest. They already have a pipeline for binaries that Skyscraper will become part of.

I believe this is mostly useful for Windows users (which I don't officially support, although I know it works under Windows). But let me know if you come up with something interesting.

It might also be useful to have prebuilt binaries for some of the more popular Linux distros and Mac.

**Comment by davestephens** [comment]
No worries dude, Skyscraper is awesome so is the least I can do.

I've been poking about with this over the last day, I started with Windows thinking it'd be the difficult one to crack but was surprisingly easy! With my test setup every commit pops out an artifact that you can just unpack and run on Windows (:boom:):

https://ci.appveyor.com/project/davestephens/skyscraper/builds/24018555/artifacts

I'd never used AppVeyor before yesterday, but it lets you do some cool things like "only publish on git tag", so you could potentially get an artifact in Appveyor for every commit, but push to GitHub releases, Chocolatey, NuGet.org etc etc when you tag the repo with a version number....

The setup I've done could do with some tweaking around versioning of the artifact etc, but if you're interested I'll raise a PR for you.

Interesting what you say RE Retropie, I didn't know they had their own build pipeline. That said, I use Recalbox and host my roms elsewhere on an Ubuntu based server, so having Skyscraper working on my Ubuntu box rather than the Recalbox RPi was key for me. I guess everyone has a different use case.

I was thinking publishing Skyscraper as a Docker image could be interesting (and easy-ish to target Windows, amd64 and ARM architectures in one hit), then there's also Snap packages which have a build pipeline for multiple architectures!

**Comment by muldjord** [comment]
Appveyor looks good. Not really sure where I want to go with this though. I'm keen on focusing entirely on coding Skyscraper. So basically you, or someone else, pretty much would have to host, maintain and test this. Which is a little much to ask I think.

The RetroPie side of things are maintained by the user "mitu" who also wrote the RetroPie script. That is very valuable to me as he takes care of the support and development of the script in cooperation with the other RetroPie guys. This would have to be similar to that.

EDIT: The artifact link doesn't seem to contain anything. Am I missing something?

**Comment by davestephens** [comment]
What you say is cool with me - my expectation is that there would be minimal effort for everyone to keep this ticking over and working :smile: 

For the Windows stuff I got working today, if you wanted to go with it you'd need to sign up to an Appveyor account (for free) then merge the PR that I'd raise with an Appveyor config file - so there's no "hosting" for anyone to manage per-se. Every time you commit something, Appveyor would automatically build and create a package. The only maintenance involved would be updating the Qt version in the Appveyor config to match the version used in the project - so very little.

How "proper" versioned releases would be built (and subsequently what happens to them) could be decided between you and I, but my expectation is that you'd follow some sort of usual practise of tagging the repo when you want a "release", which would trigger Appveyor to automatically build and trigger a push a package to the GitHub releases page.

**Comment by davestephens** [comment]
Do you not see this?
![image](https://user-images.githubusercontent.com/668464/56521294-4239b780-653d-11e9-9a53-fc506b4ceec4.png)

**Comment by muldjord** [comment]
I'm thinking of creating a separate github repository for all of this automation stuff. As not to bloat this repository it with non-code files. I'll consider this tomorrow. I'll get back to you. Thanks for taking the time to look at this.

**Comment by davestephens** [comment]
Sure, no probs. It's worth bearing in mind that you lose all of the GitHub webhook functionality (e.g auto build of a repo with 3rd party services) by moving it out to separate repo, which then makes everything a bit more manual - which is what I'm guessing you want to avoid. 

Entirely personal opinion, but I think it's pretty standard nowadays that you'll have a few bits and bobs in the repo that aren't directly code that are related to build, CI, deploy etc.

Let me know what you decide and I'll get something set up :+1:

**Comment by muldjord** [comment]
Yeah, I agree. Could you put all files related to prebuilt binaries in a subfolder called "automation" before you do any PR's on it? If it would be possible to do Windows, Mac and maybe Ubuntu that would be pretty cool. It could also make sense to have a RaspPi Stretch (I believe that's the base of RetroPie atm) prebuilt binary in there. In addition to the RetroPie script installation I also let users do manual installation (which I personally prefer), so I could potentially use a binary to ease installation for other users who prefer manual installation in RetroPie. Let me know what you think.

It suits me fine that it builts from tags. I already do all my releases based on tags, so that makes perfect sense. I just do a simple "3.1.4" style tag.

**Comment by muldjord** [comment]
Closing this. I don't have the time to maintain any of this.

**Comment by davestephens** [comment]
Apologies, I missed your last reply on this.

I'm still willing to do this work - the point being that it just runs itself, so not sure what you mean about not having time to maintain it?

**Comment by muldjord** [comment]
No need to apologize, it happens, and I appreciate the help. I thought you had left the building though, so naturally I assumed I would have to take it from here, which doesn't really have my interest. That's basically the gist of it.

So I try to focus on the stuff I find interesting myself. Major code refactoring is needed for future releases. There's a bunch of stuff I want to improve. So I'm gonna focus my attention on that.

Feel free to move on with this though if you feel like it. If it can be done without much attention from me, I am not opposed to using this if it makes sense.

**Comment by mrsilver76** [comment]
I'd be really interested in this.

For me the reason is that v3.1.5 runs on Windows 7 but not Windows 10 (I keep getting a "request timed out" error) and there looks to be a bug where the `<name>` tag always has the filename even though `--forcefilename` isn't used or defined in `config.ini`.

I'm sure it's probably fixed in a later release but I couldn't get that to compile due to my inexperience with Visual Studio and QT.

**Comment by muldjord** [comment]
I tested it on Windows 10 (I don't have Windows 7), so that sounds really weird to me. But I'll compile the latest version for you and you can try that. Stay tuned.

EDIT: I just compiled the latest 3.2.9 for Windows 10 64-bit but I can't seem to get it to actually scrape anything. So I'll need to figure that out before an updated Windows release can be uploaded.

**Comment by mrsilver76** [comment]
That would be amazing, thank you!

If I can help in any way then please shout.

**Comment by muldjord** [comment]
I've uploaded an updated Windows version that works. It was missing some OpenSSL DLL's which is what caused the network connection to timeout. So it should work for you now. Please be aware that this is a 64-bit version, so it won't work on 32-bit systems if that's what you have:
[http://www.muldjord.com/downloads/Skyscraper_3.2.9_unsupported_win_version.zip](http://www.muldjord.com/downloads/Skyscraper_3.2.9_unsupported_win_version.zip)

**Comment by mrsilver76** [comment]
Fantastic, thank you!

I'm really sorry but I won't be able to check this until the weekend - but will test on both Windows 7 (x64) and 10 (x64) and let you know.

**Comment by muldjord** [comment]
You're welcome and that would be great! Thanks!

EDIT: A quick note, I suggest running it through a Cygwin terminal if you know what that is. It supports the color escape sequences so it looks just like it does when running it under Linux. But it also works both with ye olde Windows command prompt and seemingly even under Powershell. Remember to read the README inside of the zip file before using it.

**Comment by mrsilver76** [comment]
I used to run cygwin but, since the Pi came out, it's been easier to just run Linux stuff in that.

I don't have that terminal but I do know there is an updated one coming in Windows 10 soon which might handle the escape sequences correctly.  Fingers crossed.

**Comment by mrsilver76** [comment]
I tried it with `Skyscraper.exe -p snes -s screenscraper -i d:/roms/snes -u username:password` and it worked like a charm on both Windows 7 and Windows 10.

Thank you!

I also tried it with the new Windows 10 terminal (beta) and you'll be pleased to know that the colours display correctly too :)

**Comment by muldjord** [comment]
Fantastic, thanks for testing it!

**Comment by mrsilver76** [comment]
No problem and glad to help.

The only oddity I'm getting is that, with `Skyscraper.exe -p snes -s screenscraper -i d:/roms/snes -u username:password` and no `config.ini`, I'm getting the filename in the `<name>` tag rather than the actual name.

For example this:

```
 <game>
    <path>D:/roms/snes/ActRaiser (U) [!].smc</path>
    <name>ActRaiser (U) [!]</name>
```

whereas I would have expected:

```
 <game>
    <path>D:/roms/snes/ActRaiser (U) [!].smc</path>
    <name>ActRaiser</name>
```

Is that something I'm doing wrong?

**Comment by muldjord** [comment]
The bracket notes from the filename is by default readded to the title, as they often contain useful information. You can disable them with `--nobrackets`.

I've just reupdated the Windows version to 3.3.0. I've fixed an important bug in the ScreenScraper module and introduced some neat new features, so please update. :) The new link is in the github readme.

**Comment by mrsilver76** [comment]
I'm an idiot. I saw `nobrackets` in the docs but didn't realise that it was related to just displaying the actual game name. Thanks!

3.3.0 looks good and is fast!
