### ISSUE TITLE
Skyscraper will not scrape files with a '.' in their filename

### ISSUE THREAD

**Issue by movisman** [muldjord/skyscraper#75]
Hi,

I noticed today (v2.8.1) that Skyscraper will not scrape files with a '.' in the filename (at least that's what I believe it is).

My scraping source is Screenscraper.fr. The system in question is Gamecube.

As an example, I renamed my Gamecube roms to match valid entries on Screenscraper.fr, so it would scrape based on filename. 12 out of 14 scraped fine, but two which wouldn't scrape had a dot in the filename, for example:

Super Smash Bros. Melee (USA).iso
Capcom vs. SNK 2 EO - Millionaire Fighting 2001 (USA).iso

Super Smash Bros has a couple of other matched filenames on screenscraper.fr, and when I renamed the file to one of these (in this case I tried "Dairantou Smash Brothers DX (Japan) (En,Ja) (v1.02).iso") - it scraped straight away.

Unfortunately Capcom vs. SNK has no alternative filenames without dots in them, so I cannot workaround the issue with this file or test further.

Would you agree this is a potential bug? It seems like it might be something to do with that dot.

FYI, I am using the Skyscraper tool via the RetroPie GUI.

Thanks a lot.

**Comment by muldjord** [comment]
The "." is not the issue. I scrape games such as "R.C. Grand Prix (USA, Europe).sms" just fine. I'm not sure what the issue for your use case might be then, but it is not the dot. It is rather because the filename exists for more than one platform on SS, in which case it won't return an entry. It needs to be unique for their API to return anything. Instead, try using the "--query" option as I mentioned on the retropie forums and scrape with a specific sha1 instead. That should work.
