### ISSUE TITLE
Screenscraper regression in 2.9.0 ("Driver" not matched) + wrong "unpack" behaviour for PSX/MD roms

### ISSUE THREAD

**Issue by CookiePLMonster** [muldjord/skyscraper#80]
I upgraded Skyscraper to 2.9.0 today and re-ran Screenscraper scraping with `--unpack` option, as I noticed some of my games had missing screenshots.

Then I noticed it caused havoc in PSX and MegaDrive roms:
- Most PSX roms got matched as "Point Blank", despite a) me not having this game, b) them being perfectly matched in the past.
- Most MegaDrive got matched as "Arrow Flash", with identical conditions to PSX

![screenshot-2018-33-14-12-33-18](https://user-images.githubusercontent.com/7947461/49976074-d61cc680-ff40-11e8-9461-93dad5321758.png)
![screenshot-2018-33-14-12-33-27](https://user-images.githubusercontent.com/7947461/49976076-d917b700-ff40-11e8-8a19-fbf103347786.png)
![screenshot-2018-33-14-12-33-35](https://user-images.githubusercontent.com/7947461/49976078-da48e400-ff40-11e8-9799-2cd4edee7030.png)
![screenshot-2018-33-14-12-33-50](https://user-images.githubusercontent.com/7947461/49976082-dddc6b00-ff40-11e8-9041-01c81a8f55c7.png)
![screenshot-2018-33-14-12-33-55](https://user-images.githubusercontent.com/7947461/49976081-dddc6b00-ff40-11e8-888b-64bf6f981f1c.png)

I removed `--unpack`, then backed up and purged my entire local DB and I could not reproduce it again fully, **but** I got plenty of messages about roms being not found ("Grand Theft Auto 2" got a match, but "Grand Theft Auto") **yet** they got semi-correct matches - this time title was correct, ~but there were no screenshots and genre was a "Lightgun shooter" - so Point Blank was lingering somewhere in there still.~

EDIT: Sorry, a lingering "Lightgun shooter" genre was me not purging gamelists completely. Still, there was plenty of missing data and maybe this wrong title matching can happen again.

I can try on 2.8.3 tomorrow because it's also very possible that Screenscraper is just having a bad day.

EDIT2:
Renamed the issue to reflect the latest findings.

**Comment by muldjord** [comment]
Had a look at this and analyzed the screenscraper XML response for "Demo One". The game returns a result but it's empty except for the name. I can't tell you why it's been removed, if it has. But that seems to be the reason for that showing up empty.

Concerning the unpack option, I'll need to look into it.

One question. Why are you using the --unpack option for psx when you have .cue and .m3u files in there? It doesn't make much sense to me.

EDIT: I can recreate this now, getting "Point Blank" when using --unpack. I'll look into it.

EDIT2: I've found the bug in the unpack code. Gonna fix it and release 2.9.1 during the weekend. Basically it's because I set a bool in my config to true if the --unpack option is set. Then afterwards I do some checks to see if the file is not actually a zipped file and is below a certain size (2 megs). And if it isn't, it will ignore the unpack code. Thing is, at this point the unpack bool is set to true, so it doesn't go through the normal checksumming procedure for the zip file. Instead it just ignore that code and asks directly for the checksums. And in this case I haven't added any data to the checksum function, so it basically checksums nothing. And that "nothing" will return the "Point Blank" result.

EDIT3: It's fixed on master now. I'll do testing sometime tomorrow probably and release 2.9.1 once I've run it through the paces.

**Comment by CookiePLMonster** [comment]
> I can't tell you why it's been removed, if it has. But that seems to be the reason for that showing up empty.

Do note 2.8.3 retrieves a screenshot and 2.9.0 does not. Also in the case of Driver, 2.9.0 ignores it completely. Both scrapes have been made within minutes (as soon as rpi could recompile Skyscraper), so it's not a difference in database.

> One question. Why are you using the --unpack option for psx when you have .cue and .m3u files in there? It doesn't make much sense to me.

I wanted to default to `unpack="true"` and opt out for platforms which can't use it.

Trying to bisect it by adding new tags but not much luck yet, I think my method is flawed. I'll retry tomorrow, I think.

EDIT:
I can't reproduce Driver/Demo One scraping failures anymore O_o Maybe screenscraper is really having a worse moment, or my requests have been timing out.

**Comment by muldjord** [comment]
You suddenly get full data for the "Demo One" entry again? I still don't get anything but the "Title" and that's it. But it returns a result.

EDIT: Screenscraper doesn't return any other data than the title for "Demo One" for me. Tried both 2.9.0 and 2.8.3 now. I'm pretty convinced this is not a Skyscraper issue, as it does return a result, and the result is correct. It just doesn't have any data in it.

EDIT2: Also, please take note of the edits in my previous post. I've fixed the "Point Blank" issue. Thanks for the debug help.

**Comment by muldjord** [comment]
2.9.1 tested and released. Closing issue. Let me know if you have further problems with this.

**Comment by CookiePLMonster** [comment]
Confirmed fixed, thanks!

Also now Driver is scraping fine, Demo One has nothing - so I am guessing failure in scraping Driver was either a screenscraper fluke or a timeout on my end (the other PC was downloading something then and hogging my connection, so it's likely).

Time to purge my psx and megadrive caches and re-scrape!

**Comment by CookiePLMonster** [comment]
Something may still be wrong with Demo One though - TGDB has an entry for it, yet I didn't receive it:
https://thegamesdb.net/search.php?name=Demo+One

**Comment by CookiePLMonster** [comment]
So looks like `mobygames` is not in `priorities.xml` at all - how did it pick up its screenshots then? Readme only mentions:

> If no 'priorities.xml' file is found, it will prioritize using timestamps.

But the file is here. Did it use timestamps to prioritize anyway?

EDIT:
I completely overlooked that screenshots is missing `thegamesdb`!

Since `.example` file is now being copied around to local databases, IMO it should be defined a bit better, not like an example file anymore.
